package generate

import (
	"fmt"
	"strings"

	"github.com/charmbracelet/ayo/internal/project"
)

func GenerateAgent(proj *project.Project, pkgName string) (string, error) {
	var b strings.Builder

	b.WriteString("// Code generated by ayo. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkgName))

	hasStructuredOutput := proj.Output != nil

	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"os\"\n")
	b.WriteString("\t\"path/filepath\"\n")
	b.WriteString("\t\"strings\"\n")
	b.WriteString("\n")
	b.WriteString("\t\"github.com/BurntSushi/toml\"\n")
	b.WriteString("\t\"charm.land/fantasy\"\n")
	if hasStructuredOutput {
		b.WriteString("\t\"charm.land/fantasy/object\"\n")
	}
	b.WriteString("\t\"charm.land/fantasy/providers/anthropic\"\n")
	b.WriteString("\t\"charm.land/fantasy/providers/openai\"\n")
	b.WriteString("\t\"charm.land/fantasy/providers/openaicompat\"\n")
	b.WriteString("\t\"charm.land/fantasy/providers/openrouter\"\n")
	b.WriteString(")\n\n")

	agentName := proj.Config.Name

	b.WriteString(fmt.Sprintf("// AgentConfig holds the configuration for the %s agent.\n", agentName))
	b.WriteString("type AgentConfig struct {\n")
	b.WriteString("\tProvider string\n")
	b.WriteString("\tModel    string\n")
	b.WriteString("\tAPIKey   string\n")
	b.WriteString("}\n\n")

	b.WriteString("// loadConfig loads the user configuration.\n")
	b.WriteString("func loadConfig() (*AgentConfig, error) {\n")
	b.WriteString("\tconfigDir, err := os.UserConfigDir()\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn nil, fmt.Errorf(\"getting config dir: %w\", err)\n")
	b.WriteString("\t}\n\n")
	b.WriteString(fmt.Sprintf("\tconfigPath := filepath.Join(configDir, \"agents\", \"%s.toml\")\n", agentName))
	b.WriteString("\tdata, err := os.ReadFile(configPath)\n")
	b.WriteString("\tif os.IsNotExist(err) {\n")
	b.WriteString("\t\treturn nil, nil\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn nil, fmt.Errorf(\"reading config: %w\", err)\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\tvar cfg struct {\n")
	b.WriteString("\t\tProvider string `toml:\"provider\"`\n")
	b.WriteString("\t\tModel    string `toml:\"model\"`\n")
	b.WriteString("\t\tAPIKey   string `toml:\"api_key\"`\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif _, err := toml.Decode(string(data), &cfg); err != nil {\n")
	b.WriteString("\t\treturn nil, fmt.Errorf(\"parsing config: %w\", err)\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\treturn &AgentConfig{\n")
	b.WriteString("\t\tProvider: cfg.Provider,\n")
	b.WriteString("\t\tModel:    cfg.Model,\n")
	b.WriteString("\t\tAPIKey:   cfg.APIKey,\n")
	b.WriteString("\t}, nil\n")
	b.WriteString("}\n\n")

	b.WriteString("// saveConfig saves the user configuration.\n")
	b.WriteString("func saveConfig(cfg *AgentConfig) error {\n")
	b.WriteString("\tconfigDir, err := os.UserConfigDir()\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn fmt.Errorf(\"getting config dir: %w\", err)\n")
	b.WriteString("\t}\n\n")
	b.WriteString(fmt.Sprintf("\tconfigPath := filepath.Join(configDir, \"agents\", \"%s.toml\")\n", agentName))
	b.WriteString("\tif err := os.MkdirAll(filepath.Dir(configPath), 0755); err != nil {\n")
	b.WriteString("\t\treturn fmt.Errorf(\"creating config dir: %w\", err)\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\tdata := fmt.Sprintf(\"provider = %q\\nmodel = %q\\napi_key = %q\\n\",\n")
	b.WriteString("\t\tcfg.Provider, cfg.Model, cfg.APIKey)\n")
	b.WriteString("\treturn os.WriteFile(configPath, []byte(data), 0600)\n")
	b.WriteString("}\n\n")

	b.WriteString("// ensureConfig ensures a valid configuration exists.\n")
	b.WriteString("func ensureConfig() error {\n")
	b.WriteString("\tcfg, err := loadConfig()\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn err\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\tif cfg != nil && cfg.Provider != \"\" && cfg.Model != \"\" {\n")
	b.WriteString("\t\treturn nil\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\tif provider != \"\" && model != \"\" {\n")
	b.WriteString("\t\tapiKey := os.Getenv(getAPIKeyEnv(provider))\n")
	b.WriteString("\t\tnewCfg := &AgentConfig{\n")
	b.WriteString("\t\t\tProvider: provider,\n")
	b.WriteString("\t\t\tModel:    model,\n")
	b.WriteString("\t\t\tAPIKey:   apiKey,\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\treturn saveConfig(newCfg)\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\treturn selectModel()\n")
	b.WriteString("}\n\n")

	b.WriteString("// selectModel launches the model selection TUI.\n")
	b.WriteString("func selectModel() error {\n")
	b.WriteString("\treturn runModelSelectionTUI()\n")
	b.WriteString("}\n\n")
	b.WriteString("// scanAvailableProviders checks environment for available API keys.\n")
	b.WriteString("func scanAvailableProviders() []string {\n")
	b.WriteString("\tvar available []string\n")
	b.WriteString("\tfor _, p := range []string{\"anthropic\", \"openai\", \"zai\", \"openrouter\", \"gemini\", \"groq\"} {\n")
	b.WriteString("\t\tif key := os.Getenv(getAPIKeyEnv(p)); strings.TrimSpace(key) != \"\" {\n")
	b.WriteString("\t\t\tavailable = append(available, p)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn available\n")
	b.WriteString("}\n\n")
	b.WriteString("// getDefaultModel returns the default model for a provider.\n")
	b.WriteString("func getDefaultModel(provider string) string {\n")
	b.WriteString("\tmodels := map[string]string{\n")
	b.WriteString("\t\t\"anthropic\":  \"claude-3-5-sonnet-20241022\",\n")
	b.WriteString("\t\t\"openai\":     \"gpt-4o\",\n")
	b.WriteString("\t\t\"zai\":        \"zai-v4\",\n")
	b.WriteString("\t\t\"openrouter\": \"anthropic/claude-3.5-sonnet\",\n")
	b.WriteString("\t\t\"gemini\":     \"gemini-1.5-pro\",\n")
	b.WriteString("\t\t\"groq\":       \"llama-3.3-70b-versatile\",\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif m, ok := models[provider]; ok {\n")
	b.WriteString("\t\treturn m\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn \"\"\n")
	b.WriteString("}\n\n")

	b.WriteString("// getAPIKeyEnv returns the environment variable name for a provider.\n")
	b.WriteString("func getAPIKeyEnv(p string) string {\n")
	b.WriteString("\tswitch p {\n")
	b.WriteString("\tcase \"anthropic\":\n")
	b.WriteString("\t\treturn \"ANTHROPIC_API_KEY\"\n")
	b.WriteString("\tcase \"openai\":\n")
	b.WriteString("\t\treturn \"OPENAI_API_KEY\"\n")
	b.WriteString("\tcase \"gemini\":\n")
	b.WriteString("\t\treturn \"GEMINI_API_KEY\"\n")
	b.WriteString("\tcase \"groq\":\n")
	b.WriteString("\t\treturn \"GROQ_API_KEY\"\n")
	b.WriteString("\tcase \"openrouter\":\n")
	b.WriteString("\t\treturn \"OPENROUTER_API_KEY\"\n")
	b.WriteString("\tcase \"zai\":\n")
	b.WriteString("\t\treturn \"ZAI_API_KEY\"\n")
	b.WriteString("\tdefault:\n")
	b.WriteString("\t\treturn strings.ToUpper(p) + \"_API_KEY\"\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	hasInput := proj.Input != nil

	// Generate executeAgent function signature based on input/output configuration
	b.WriteString("// executeAgent runs the agent with the given input.\n")
	if hasInput {
		if hasStructuredOutput {
			b.WriteString("func executeAgent(ctx context.Context, input Input) (*Output, error) {\n")
		} else {
			b.WriteString("func executeAgent(ctx context.Context, input Input) (string, error) {\n")
		}
	} else {
		if hasStructuredOutput {
			b.WriteString("func executeAgent(ctx context.Context, input string) (*Output, error) {\n")
		} else {
			b.WriteString("func executeAgent(ctx context.Context, input string) (string, error) {\n")
		}
	}

	b.WriteString("\tcfg, err := loadConfig()\n")
	b.WriteString("\tif err != nil {\n")
	if proj.Output != nil {
		b.WriteString("\t\treturn nil, err\n")
	} else {
		b.WriteString("\t\treturn \"\", err\n")
	}
	b.WriteString("\t}\n")
	b.WriteString("\tif cfg == nil {\n")
	if proj.Output != nil {
		b.WriteString("\t\treturn nil, fmt.Errorf(\"no configuration found - run the agent interactively to set up\")\n")
	} else {
		b.WriteString("\t\treturn \"\", fmt.Errorf(\"no configuration found - run the agent interactively to set up\")\n")
	}
	b.WriteString("\t}\n\n")

	// Initialize hook runner if hooks exist
	if len(proj.Hooks) > 0 {
		b.WriteString("\t// Initialize hook runner\n")
		b.WriteString("\thooks := initHooks()\n")
		b.WriteString("\t_ = hooks // Hook runner ready for use\n\n")
	}

	// Provider creation
	b.WriteString("\t// Create provider based on configuration\n")
	b.WriteString("\tvar provider fantasy.Provider\n")
	b.WriteString("\tswitch cfg.Provider {\n")
	b.WriteString("\tcase \"anthropic\":\n")
	b.WriteString("\t\tprovider, err = anthropic.New(anthropic.WithAPIKey(cfg.APIKey))\n")
	b.WriteString("\tcase \"openai\":\n")
	b.WriteString("\t\tprovider, err = openai.New(openai.WithAPIKey(cfg.APIKey))\n")
	b.WriteString("\tcase \"zai\":\n")
	b.WriteString("\t\tprovider, err = openaicompat.New(\n")
	b.WriteString("\t\t\topenaicompat.WithAPIKey(cfg.APIKey),\n")
	b.WriteString("\t\t\topenaicompat.WithBaseURL(\"https://api.z.ai/api/coding/paas/v4\"),\n")
	b.WriteString("\t\t\topenaicompat.WithName(\"zai\"),\n")
	b.WriteString("\t\t)\n")
	b.WriteString("\tcase \"openrouter\":\n")
	b.WriteString("\t\tprovider, err = openrouter.New(openrouter.WithAPIKey(cfg.APIKey))\n")
	b.WriteString("\tdefault:\n")
	b.WriteString("\t\terr = fmt.Errorf(\"unsupported provider: %s\", cfg.Provider)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif err != nil {\n")
	if proj.Output != nil {
		b.WriteString("\t\treturn nil, fmt.Errorf(\"creating provider: %w\", err)\n")
	} else {
		b.WriteString("\t\treturn \"\", fmt.Errorf(\"creating provider: %w\", err)\n")
	}
	b.WriteString("\t}\n\n")

	// Get model from provider
	b.WriteString("\t// Get language model\n")
	b.WriteString("\tmodel, err := provider.LanguageModel(ctx, cfg.Model)\n")
	b.WriteString("\tif err != nil {\n")
	if proj.Output != nil {
		b.WriteString("\t\treturn nil, fmt.Errorf(\"getting model: %w\", err)\n")
	} else {
		b.WriteString("\t\treturn \"\", fmt.Errorf(\"getting model: %w\", err)\n")
	}
	b.WriteString("\t}\n\n")

	// Prepare prompt
	b.WriteString("\tprompt := renderPrompt(input)\n")
	b.WriteString("\tsystem := getSystemMessage()\n\n")

	if hasStructuredOutput {
		// Structured output using object.Generate
		b.WriteString("\t// Generate structured output\n")
		b.WriteString("\tresult, err := object.Generate[Output](ctx, model, fantasy.ObjectCall{\n")
		b.WriteString("\t\tPrompt: fantasy.Prompt{\n")
		b.WriteString("\t\t\tfantasy.NewSystemMessage(system),\n")
		b.WriteString("\t\t\tfantasy.NewUserMessage(prompt),\n")
		b.WriteString("\t\t},\n")
		b.WriteString("\t})\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\treturn nil, fmt.Errorf(\"generating output: %w\", err)\n")
		b.WriteString("\t}\n\n")
		b.WriteString("\treturn &result.Object, nil\n")
	} else {
		// Text output using agent
		b.WriteString("\t// Create agent and generate text response\n")
		b.WriteString("\tagent := fantasy.NewAgent(model, fantasy.WithSystemPrompt(system))\n")
		b.WriteString("\tresult, err := agent.Generate(ctx, fantasy.AgentCall{Prompt: prompt})\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\treturn \"\", fmt.Errorf(\"generating response: %w\", err)\n")
		b.WriteString("\t}\n\n")
		b.WriteString("\treturn result.Response.Content.Text(), nil\n")
	}
	b.WriteString("}\n")

	return b.String(), nil
}

func (g *Generator) GenerateMain(proj *project.Project) (string, error) {
	var b strings.Builder

	b.WriteString("// Code generated by ayo. DO NOT EDIT.\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("import \"os\"\n\n")
	b.WriteString("func main() {\n")
	b.WriteString("\tif err := Execute(); err != nil {\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")

	return b.String(), nil
}

type Generator struct{}

func NewGenerator() *Generator {
	return &Generator{}
}

func (g *Generator) Generate(project *project.Project, pkgName string) (map[string]string, error) {
	files := make(map[string]string)

	cli, err := GenerateCLI(project, pkgName)
	if err != nil {
		return nil, fmt.Errorf("generating CLI: %w", err)
	}
	files["cli.go"] = cli

	agent, err := GenerateAgent(project, pkgName)
	if err != nil {
		return nil, fmt.Errorf("generating agent: %w", err)
	}
	files["agent.go"] = agent

	embeds, err := GenerateEmbeds(project, pkgName)
	if err != nil {
		return nil, fmt.Errorf("generating embeds: %w", err)
	}
	files["embed.go"] = embeds

	tui, err := GenerateTUI(project, pkgName)
	if err != nil {
		return nil, fmt.Errorf("generating TUI: %w", err)
	}
	files["tui.go"] = tui

	if len(project.Hooks) > 0 {
		hooks, err := GenerateHooks(project, pkgName)
		if err != nil {
			return nil, fmt.Errorf("generating hooks: %w", err)
		}
		files["hooks.go"] = hooks
	}

	main, err := g.GenerateMain(project)
	if err != nil {
		return nil, fmt.Errorf("generating main: %w", err)
	}
	files["main.go"] = main

	return files, nil
}
