package generate

import (
	"fmt"
	"strings"

	"github.com/ayo-ooo/ayo/internal/project"
	"github.com/ayo-ooo/ayo/internal/schema"
)

func GenerateCLI(proj *project.Project, pkgName string) (string, error) {
	var b strings.Builder

	hasInput := proj.Input != nil
	hasOutput := proj.Output != nil
	agentInteractive := proj.Config.IsInteractive()

	b.WriteString("// Code generated by ayo. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkgName))
	b.WriteString("import (\n")
	if hasInput || hasOutput {
		b.WriteString("\t\"encoding/json\"\n")
	}
	b.WriteString("\t\"fmt\"\n")
	if hasInput {
		b.WriteString("\t\"io\"\n")
		b.WriteString("\t\"strings\"\n")
	}
	b.WriteString("\t\"os\"\n")
	b.WriteString("\n")
	b.WriteString("\t\"charm.land/huh/v2\"\n")
	b.WriteString("\n")
	b.WriteString("\t\"github.com/spf13/cobra\"\n")
	b.WriteString(")\n\n")

	agentName := proj.Config.Name

	// Generate variable declarations for flags
	b.WriteString("var (\n")
	b.WriteString("\tjsonInput string\n")
	b.WriteString("\tnonInteractive bool\n")
	if proj.Input != nil {
		inputSchema := proj.Input.Parsed.(*schema.ParsedSchema)
		for name, prop := range inputSchema.Properties {
			if !schema.IsPrimitiveType(prop.Type) {
				continue
			}
			goType := jsonTypeToGo(prop.Type)
			b.WriteString(fmt.Sprintf("\t%s %s\n", toCamelCase(name), goType))
		}
	}
	b.WriteString("\toutputPath string\n")
	b.WriteString("\tprovider string\n")
	b.WriteString("\tmodel string\n")
	b.WriteString(")\n\n")

	// Generate agent config constants
	b.WriteString(fmt.Sprintf("var agentInteractive = %v\n", agentInteractive))
	if hasInput {
		b.WriteString("// propertyInfo holds schema property metadata\n")
		b.WriteString("var propertyInfo = map[string]struct{ desc string; req bool }{\n")
		inputSchema := proj.Input.Parsed.(*schema.ParsedSchema)
		for name, prop := range inputSchema.Properties {
			required := false
			for _, r := range inputSchema.Required {
				if r == name {
					required = true
					break
				}
			}
			b.WriteString(fmt.Sprintf("\t%q: {%q, %v},\n", name, escapeString(prop.Description), required))
		}
		b.WriteString("}\n\n")
	}

	// Generate root command with json-input placeholder
	b.WriteString(fmt.Sprintf("var rootCmd = &cobra.Command{\n"))
	b.WriteString(fmt.Sprintf("\tUse:   \"%s [json-input]\",\n", agentName))
	b.WriteString(fmt.Sprintf("\tShort: \"%s\",\n", escapeString(proj.Config.Description)))
	b.WriteString(fmt.Sprintf("\tRun:   runAgent,\n"))
	b.WriteString("}\n\n")

	// Generate flag registrations
	b.WriteString("func init() {\n")
	if proj.Input != nil {
		inputSchema := proj.Input.Parsed.(*schema.ParsedSchema)
		flags := schema.GenerateFlags(inputSchema)
		for _, flag := range flags {
			b.WriteString(generateFlagCode(flag))
		}
	}
	b.WriteString("\trootCmd.Flags().StringVarP(&outputPath, \"output\", \"o\", \"\", \"Write output to file\")\n")
	b.WriteString("\trootCmd.Flags().StringVar(&provider, \"provider\", \"\", \"AI provider to use\")\n")
	b.WriteString("\trootCmd.Flags().StringVar(&model, \"model\", \"\", \"Model to use\")\n")
	b.WriteString("\trootCmd.Flags().BoolVar(&nonInteractive, \"non-interactive\", false, \"Disable interactive form\")\n")
	b.WriteString("}\n\n")

	b.WriteString("func Execute() error {\n")
	b.WriteString("\treturn rootCmd.Execute()\n")
	b.WriteString("}\n\n")

	// Generate runAgent function with interactive form support
	b.WriteString("func runAgent(cmd *cobra.Command, args []string) {\n")
	b.WriteString("\tctx := cmd.Context()\n\n")
	b.WriteString("\tif err := ensureConfig(); err != nil {\n")
	b.WriteString("\t\tfmt.Fprintln(os.Stderr, err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n\n")

	if hasInput {
		// Generate code to check for missing required fields
		b.WriteString("\t// Check for missing required fields\n")
		b.WriteString("\tmissing := getMissingRequiredFields()\n")
		b.WriteString("\tif len(missing) > 0 {\n")
		b.WriteString("\t\tif shouldShowForm() {\n")
		b.WriteString("\t\t\tprefill := collectPrefillValues()\n")
		b.WriteString("\t\t\tform := createForm(prefill)\n")
		b.WriteString("\t\t\tif err := form.Run(); err != nil {\n")
		b.WriteString("\t\t\t\tfmt.Fprintln(os.Stderr, err)\n")
		b.WriteString("\t\t\t\tos.Exit(1)\n")
		b.WriteString("\t\t\t}\n")
		b.WriteString("\t\t\tapplyFormResults(form)\n")
		b.WriteString("\t\t} else {\n")
		b.WriteString("\t\t\tfmt.Fprintln(os.Stderr, formatMissingArgs(missing))\n")
		b.WriteString("\t\t\tos.Exit(1)\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n\n")
	} else {
		// No input schema - show free-form prompt
		b.WriteString("\t// No input schema - show free-form prompt\n")
		b.WriteString("\tif len(args) == 0 && jsonInput == \"\" {\n")
		b.WriteString("\t\tif shouldShowForm() {\n")
		b.WriteString("\t\t\tvar freeFormPrompt string\n")
		b.WriteString("\t\t\tform := huh.NewForm(\n")
		b.WriteString("\t\t\t\thuh.NewGroup(\n")
		b.WriteString("\t\t\t\t\thuh.NewText().\n")
		b.WriteString("\t\t\t\t\t\tTitle(\"What would you like to do?\").\n")
		b.WriteString("\t\t\t\t\t\tValue(&freeFormPrompt),\n")
		b.WriteString("\t\t\t\t),\n")
		b.WriteString("\t\t\t)\n")
		b.WriteString("\t\t\tif err := form.Run(); err != nil {\n")
		b.WriteString("\t\t\t\tfmt.Fprintln(os.Stderr, err)\n")
		b.WriteString("\t\t\t\tos.Exit(1)\n")
		b.WriteString("\t\t\t}\n")
		b.WriteString("\t\t\tjsonInput = freeFormPrompt\n")
		b.WriteString("\t\t} else {\n")
		b.WriteString("\t\t\tfmt.Fprintln(os.Stderr, \"No prompt provided. Run with --help for usage.\")\n")
		b.WriteString("\t\t\tos.Exit(1)\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n\n")
	}

	b.WriteString("\tinputData := buildInput(args)\n")
	b.WriteString("\tresult, err := executeAgent(ctx, inputData)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tfmt.Fprintln(os.Stderr, err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n\n")

	if proj.Output != nil {
		b.WriteString("\toutput, err := json.Marshal(result)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\tfmt.Fprintln(os.Stderr, err)\n")
		b.WriteString("\t\tos.Exit(1)\n")
		b.WriteString("\t}\n\n")

		b.WriteString("\tfmt.Println(string(output))\n")
		b.WriteString("\tif outputPath != \"\" {\n")
		b.WriteString("\t\tif err := os.WriteFile(outputPath, output, 0644); err != nil {\n")
		b.WriteString("\t\t\tfmt.Fprintln(os.Stderr, err)\n")
		b.WriteString("\t\t\tos.Exit(1)\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n")
	} else {
		b.WriteString("\tfmt.Println(result)\n")
		b.WriteString("\tif outputPath != \"\" {\n")
		b.WriteString("\t\tif err := os.WriteFile(outputPath, []byte(result), 0644); err != nil {\n")
		b.WriteString("\t\t\tfmt.Fprintln(os.Stderr, err)\n")
		b.WriteString("\t\t\tos.Exit(1)\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n")
	}
	b.WriteString("}\n\n")

	// Generate helper functions for interactive mode
	b.WriteString(generateInteractiveHelpers(agentInteractive, hasInput))

	// Generate buildInput function with JSON parsing and flag overrides
	b.WriteString("func buildInput(args []string) ")
	if proj.Input != nil {
		b.WriteString("Input {\n")
		b.WriteString("\tvar input Input\n\n")
		b.WriteString("\t// 1. Parse JSON payload if provided\n")
		b.WriteString("\tif len(args) > 0 {\n")
		b.WriteString("\t\tvar jsonData []byte\n")
		b.WriteString("\t\tvar err error\n")
		b.WriteString("\t\tif args[0] == \"-\" {\n")
		b.WriteString("\t\t\tjsonData, err = io.ReadAll(os.Stdin)\n")
		b.WriteString("\t\t\tif err != nil {\n")
		b.WriteString("\t\t\t\tfmt.Fprintf(os.Stderr, \"Error reading stdin: %%v\\n\", err)\n")
		b.WriteString("\t\t\t\tos.Exit(1)\n")
		b.WriteString("\t\t\t}\n")
		b.WriteString("\t\t} else {\n")
		b.WriteString("\t\t\tjsonData = []byte(args[0])\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t\tif err := json.Unmarshal(jsonData, &input); err != nil {\n")
		b.WriteString("\t\t\tfmt.Fprintf(os.Stderr, \"Error parsing JSON: %%v\\n\", err)\n")
		b.WriteString("\t\t\tos.Exit(1)\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n\n")
		b.WriteString("\t// 2. Apply flag overrides\n")
		inputSchema := proj.Input.Parsed.(*schema.ParsedSchema)
		for name, prop := range inputSchema.Properties {
			if !schema.IsPrimitiveType(prop.Type) {
				continue
			}
			camelName := toCamelCase(name)
			pascalName := toPascalCase(name)
			switch prop.Type {
			case "string":
				b.WriteString(fmt.Sprintf("\tif %s != \"\" {\n\t\tinput.%s = %s\n\t}\n", camelName, pascalName, camelName))
			case "boolean":
				b.WriteString(fmt.Sprintf("\tif %s {\n\t\tinput.%s = %s\n\t}\n", camelName, pascalName, camelName))
			case "integer", "number":
				b.WriteString(fmt.Sprintf("\tif %s != 0 {\n\t\tinput.%s = %s\n\t}\n", camelName, pascalName, camelName))
			}
		}
		b.WriteString("\n\treturn input\n")
	} else {
		b.WriteString("string {\n")
		b.WriteString("\tif len(args) > 0 {\n")
		b.WriteString("\t\treturn args[0]\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn jsonInput\n")
	}
	b.WriteString("}\n")

	return b.String(), nil
}

func generateFlagCode(flag schema.FlagDef) string {
	var b strings.Builder
	flagName := strings.TrimPrefix(flag.Name, "--")
	varName := toCamelCase(flag.PropertyName)

	switch flag.Type {
	case "boolean":
		defVal := false
		if v, ok := flag.DefaultValue.(bool); ok {
			defVal = v
		}
		b.WriteString(fmt.Sprintf("\trootCmd.Flags().BoolVar(&%s, \"%s\", %v, \"%s\")\n",
			varName, flagName, defVal, escapeString(flag.Description)))
	case "integer":
		defVal := 0
		if v, ok := flag.DefaultValue.(float64); ok {
			defVal = int(v)
		}
		b.WriteString(fmt.Sprintf("\trootCmd.Flags().IntVar(&%s, \"%s\", %d, \"%s\")\n",
			varName, flagName, defVal, escapeString(flag.Description)))
	case "number":
		defVal := 0.0
		if v, ok := flag.DefaultValue.(float64); ok {
			defVal = v
		}
		b.WriteString(fmt.Sprintf("\trootCmd.Flags().Float64Var(&%s, \"%s\", %v, \"%s\")\n",
			varName, flagName, defVal, escapeString(flag.Description)))
	default:
		defVal := ""
		if v, ok := flag.DefaultValue.(string); ok {
			defVal = v
		}
		b.WriteString(fmt.Sprintf("\trootCmd.Flags().StringVar(&%s, \"%s\", \"%s\", \"%s\")\n",
			varName, flagName, defVal, escapeString(flag.Description)))
	}

	return b.String()
}

func generateInteractiveHelpers(agentInteractive, hasInput bool) string {
	var b strings.Builder

	// isTerminal
	b.WriteString(`func isTerminal() bool {
	fi, err := os.Stdout.Stat()
	if err != nil {
		return false
	}
	return (fi.Mode() & os.ModeCharDevice) != 0
}

`)

	// shouldShowForm
	b.WriteString(fmt.Sprintf(`func shouldShowForm() bool {
	if nonInteractive {
		return false
	}
	if !%v {
		return false
	}
	return isTerminal()
}

`, agentInteractive))

	if hasInput {
		// getMissingRequiredFields
		b.WriteString(`func getMissingRequiredFields() []string {
	var missing []string
	for name, info := range propertyInfo {
		if !info.req {
			continue
		}
		switch name {
`)
		// This is a simplified version - we need the actual schema to generate proper checks
		// For now, return a basic implementation
		b.WriteString("\t\tdefault:\n\t\t\t// Check based on flag value\n\t\t}\n\t}\n\treturn missing\n}\n\n")

		// formatMissingArgs
		b.WriteString(`func formatMissingArgs(missing []string) string {
	var b strings.Builder
	b.WriteString("Missing required arguments:\n\n")
	for _, name := range missing {
		info := propertyInfo[name]
		desc := info.desc
		if desc == "" {
			desc = name
		}
		b.WriteString(fmt.Sprintf("  --%-15s %s\n", name, desc))
	}
	b.WriteString("\nRun with --help for usage information.")
	return b.String()
}

`)

		// collectPrefillValues
		b.WriteString(`func collectPrefillValues() map[string]any {
	return map[string]any{}
}

`)

		// createForm
		b.WriteString(`func createForm(prefill map[string]any) *huh.Form {
	return huh.NewForm(huh.NewGroup())
}

`)

		// applyFormResults
		b.WriteString(`func applyFormResults(form *huh.Form) {
	// Apply form results to flags
}

`)
	}

	return b.String()
}
