package generate

import (
	"fmt"
	"strings"

	"github.com/ayo-ooo/ayo/internal/project"
	"github.com/ayo-ooo/ayo/internal/schema"
)

func GenerateCLI(proj *project.Project, pkgName string) (string, error) {
	var b strings.Builder

	hasInput := proj.Input != nil
	_ = proj.Output // Output schema is handled by agent.go
	agentInteractive := proj.Config.IsInteractive()

	b.WriteString("// Code generated by ayo. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkgName))
	b.WriteString("import (\n")
	if hasInput {
		b.WriteString("\t\"encoding/json\"\n")
	}
	b.WriteString("\t\"fmt\"\n")
	if hasInput {
		b.WriteString("\t\"io\"\n")
	}
	b.WriteString("\t\"os\"\n")
	if hasInput {
		// Check if strconv is needed (numeric form fields)
		needsStrconv := false
		if proj.Input != nil {
			inputSchema := proj.Input.Parsed.(*schema.ParsedSchema)
			for _, prop := range inputSchema.Properties {
				if prop.Type == "integer" || prop.Type == "number" {
					needsStrconv = true
					break
				}
			}
		}
		if needsStrconv {
			b.WriteString("\t\"strconv\"\n")
		}
		b.WriteString("\t\"strings\"\n")
	}
	b.WriteString("\n")
	b.WriteString("\t\"charm.land/huh/v2\"\n")
	b.WriteString("\n")
	b.WriteString("\t\"github.com/spf13/cobra\"\n")
	b.WriteString(")\n\n")

	agentName := proj.Config.Name

	isConversational := !hasInput

	// Generate variable declarations for flags
	b.WriteString("var (\n")
	b.WriteString("\tjsonInput string\n")
	b.WriteString("\tnonInteractive bool\n")
	b.WriteString("\tayoDescribe bool\n")
	if proj.Input != nil {
		inputSchema := proj.Input.Parsed.(*schema.ParsedSchema)
		for name, prop := range inputSchema.Properties {
			if !schema.IsPrimitiveType(prop.Type) {
				continue
			}
			goType := jsonTypeToGo(prop.Type)
			b.WriteString(fmt.Sprintf("\t%s %s\n", toCamelCase(name), goType))
		}
	}
	if isConversational {
		b.WriteString("\tsessionID string\n")
		b.WriteString("\tchatMode bool\n")
	}
	b.WriteString("\toutputPath string\n")
	b.WriteString("\tprovider string\n")
	b.WriteString("\tmodel string\n")
	b.WriteString(")\n\n")

	// Generate agent config constants
	b.WriteString(fmt.Sprintf("var agentInteractive = %v\n", agentInteractive))
	if hasInput {
		b.WriteString("// propertyInfo holds schema property metadata\n")
		b.WriteString("var propertyInfo = map[string]struct{ desc string; req bool }{\n")
		inputSchema := proj.Input.Parsed.(*schema.ParsedSchema)
		for name, prop := range inputSchema.Properties {
			required := false
			for _, r := range inputSchema.Required {
				if r == name {
					required = true
					break
				}
			}
			b.WriteString(fmt.Sprintf("\t%q: {%q, %v},\n", name, escapeString(prop.Description), required))
		}
		b.WriteString("}\n\n")
	}

	// Generate root command with json-input placeholder
	b.WriteString(fmt.Sprintf("var rootCmd = &cobra.Command{\n"))
	b.WriteString(fmt.Sprintf("\tUse:   \"%s [json-input]\",\n", agentName))
	b.WriteString(fmt.Sprintf("\tShort: \"%s\",\n", escapeString(proj.Config.Description)))
	b.WriteString(fmt.Sprintf("\tRun:   runAgent,\n"))
	b.WriteString("}\n\n")

	// Generate flag registrations
	b.WriteString("func init() {\n")
	if proj.Input != nil {
		inputSchema := proj.Input.Parsed.(*schema.ParsedSchema)
		flags := schema.GenerateFlags(inputSchema)
		for _, flag := range flags {
			b.WriteString(generateFlagCode(flag))
		}
	}
	b.WriteString("\trootCmd.Flags().StringVarP(&outputPath, \"output\", \"o\", \"\", \"Write output to file\")\n")
	b.WriteString("\trootCmd.Flags().StringVar(&provider, \"provider\", \"\", \"AI provider to use\")\n")
	b.WriteString("\trootCmd.Flags().StringVar(&model, \"model\", \"\", \"Model to use\")\n")
	b.WriteString("\trootCmd.Flags().BoolVar(&nonInteractive, \"non-interactive\", false, \"Disable interactive form\")\n")
	b.WriteString("\trootCmd.Flags().BoolVar(&ayoDescribe, \"ayo-describe\", false, \"Output agent metadata as JSON\")\n")
	b.WriteString("\trootCmd.Flags().MarkHidden(\"ayo-describe\")\n")
	if isConversational {
		b.WriteString("\trootCmd.Flags().StringVar(&sessionID, \"session\", \"\", \"Resume a conversation session by ID\")\n")
		b.WriteString("\trootCmd.Flags().BoolVar(&chatMode, \"chat\", false, \"Start interactive chat mode\")\n")
	}
	b.WriteString("}\n\n")

	b.WriteString("func Execute() error {\n")
	b.WriteString("\treturn rootCmd.Execute()\n")
	b.WriteString("}\n\n")

	// Generate runAgent function with interactive form support
	b.WriteString("func runAgent(cmd *cobra.Command, args []string) {\n")
	b.WriteString("\t// Self-description protocol: output metadata and exit\n")
	b.WriteString("\tif ayoDescribe {\n")
	b.WriteString("\t\tfmt.Println(ayoMetadata)\n")
	b.WriteString("\t\tos.Exit(0)\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\tctx := cmd.Context()\n\n")
	b.WriteString("\tif err := ensureConfig(); err != nil {\n")
	b.WriteString("\t\tfmt.Fprintln(os.Stderr, err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n\n")

	if hasInput {
		// Generate code to check for missing required fields
		b.WriteString("\t// Check for missing required fields\n")
		b.WriteString("\tmissing := getMissingRequiredFields()\n")
		b.WriteString("\tif len(missing) > 0 {\n")
		b.WriteString("\t\tif shouldShowForm() {\n")
		b.WriteString("\t\t\tprefill := collectPrefillValues()\n")
		b.WriteString("\t\t\tform := createForm(prefill)\n")
		b.WriteString("\t\t\tif err := form.Run(); err != nil {\n")
		b.WriteString("\t\t\t\tfmt.Fprintln(os.Stderr, err)\n")
		b.WriteString("\t\t\t\tos.Exit(1)\n")
		b.WriteString("\t\t\t}\n")
		b.WriteString("\t\t\tapplyFormResults(form)\n")
		b.WriteString("\t\t} else {\n")
		b.WriteString("\t\t\tfmt.Fprintln(os.Stderr, formatMissingArgs(missing))\n")
		b.WriteString("\t\t\tos.Exit(1)\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n\n")
	} else {
		// No input schema - conversational agent
		b.WriteString("\t// Conversational agent - supports --session and --chat\n\n")

		// Chat mode handling
		b.WriteString("\tif chatMode {\n")
		b.WriteString("\t\trunChatMode(ctx)\n")
		b.WriteString("\t\treturn\n")
		b.WriteString("\t}\n\n")

		// Get prompt from args or interactive form
		b.WriteString("\tprompt := \"\"\n")
		b.WriteString("\tif len(args) > 0 {\n")
		b.WriteString("\t\tprompt = args[0]\n")
		b.WriteString("\t} else if jsonInput != \"\" {\n")
		b.WriteString("\t\tprompt = jsonInput\n")
		b.WriteString("\t} else {\n")
		b.WriteString("\t\tif shouldShowForm() {\n")
		b.WriteString("\t\t\tvar freeFormPrompt string\n")
		b.WriteString("\t\t\tform := huh.NewForm(\n")
		b.WriteString("\t\t\t\thuh.NewGroup(\n")
		b.WriteString("\t\t\t\t\thuh.NewText().\n")
		b.WriteString("\t\t\t\t\t\tTitle(\"What would you like to do?\").\n")
		b.WriteString("\t\t\t\t\t\tValue(&freeFormPrompt),\n")
		b.WriteString("\t\t\t\t),\n")
		b.WriteString("\t\t\t)\n")
		b.WriteString("\t\t\tif err := form.Run(); err != nil {\n")
		b.WriteString("\t\t\t\tfmt.Fprintln(os.Stderr, err)\n")
		b.WriteString("\t\t\t\tos.Exit(1)\n")
		b.WriteString("\t\t\t}\n")
		b.WriteString("\t\t\tprompt = freeFormPrompt\n")
		b.WriteString("\t\t} else {\n")
		b.WriteString("\t\t\tfmt.Fprintln(os.Stderr, \"No prompt provided. Run with --help for usage.\")\n")
		b.WriteString("\t\t\tos.Exit(1)\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n\n")

		// Session handling
		b.WriteString("\t// Load or create session if --session flag is provided\n")
		b.WriteString("\tvar history []SessionMessage\n")
		b.WriteString("\tif sessionID != \"\" {\n")
		b.WriteString("\t\thistory = loadSession(sessionID)\n")
		b.WriteString("\t}\n\n")

		b.WriteString("\t// Execute with history\n")
		b.WriteString("\tresult, err := executeAgentWithMessages(ctx, prompt, history)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\tfmt.Fprintln(os.Stderr, err)\n")
		b.WriteString("\t\tos.Exit(1)\n")
		b.WriteString("\t}\n\n")

		// Save session
		b.WriteString("\tif sessionID != \"\" {\n")
		b.WriteString("\t\thistory = append(history, SessionMessage{Role: \"user\", Content: prompt})\n")
		b.WriteString("\t\thistory = append(history, SessionMessage{Role: \"assistant\", Content: result})\n")
		b.WriteString("\t\tsaveSession(sessionID, history)\n")
		b.WriteString("\t}\n\n")

		b.WriteString("\tfmt.Println(result)\n")
		b.WriteString("\tif outputPath != \"\" {\n")
		b.WriteString("\t\tif err := os.WriteFile(outputPath, []byte(result), 0644); err != nil {\n")
		b.WriteString("\t\t\tfmt.Fprintln(os.Stderr, err)\n")
		b.WriteString("\t\t\tos.Exit(1)\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n")
		b.WriteString("}\n\n")

		// Generate helper functions for conversational mode
		b.WriteString(generateFreeformHelpers(agentInteractive))

		return b.String(), nil
	}

	b.WriteString("\tinputData := buildInput(args)\n")
	b.WriteString("\tresult, err := executeAgent(ctx, inputData)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tfmt.Fprintln(os.Stderr, err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n\n")

	if proj.Output != nil {
		b.WriteString("\toutput, err := json.Marshal(result)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\tfmt.Fprintln(os.Stderr, err)\n")
		b.WriteString("\t\tos.Exit(1)\n")
		b.WriteString("\t}\n\n")

		b.WriteString("\tfmt.Println(string(output))\n")
		b.WriteString("\tif outputPath != \"\" {\n")
		b.WriteString("\t\tif err := os.WriteFile(outputPath, output, 0644); err != nil {\n")
		b.WriteString("\t\t\tfmt.Fprintln(os.Stderr, err)\n")
		b.WriteString("\t\t\tos.Exit(1)\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n")
	} else {
		b.WriteString("\tfmt.Println(result)\n")
		b.WriteString("\tif outputPath != \"\" {\n")
		b.WriteString("\t\tif err := os.WriteFile(outputPath, []byte(result), 0644); err != nil {\n")
		b.WriteString("\t\t\tfmt.Fprintln(os.Stderr, err)\n")
		b.WriteString("\t\t\tos.Exit(1)\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n")
	}
	b.WriteString("}\n\n")

	// Generate helper functions for interactive mode
	if hasInput {
		inputSchema := proj.Input.Parsed.(*schema.ParsedSchema)
		b.WriteString(generateWorkingInteractiveHelpers(agentInteractive, inputSchema, proj.Config.InputOrder))
	} else {
		b.WriteString(generateFreeformHelpers(agentInteractive))
	}

	// Generate buildInput function with JSON parsing, flag overrides, and pipe detection
	b.WriteString("func buildInput(args []string) ")
	if proj.Input != nil {
		b.WriteString("Input {\n")
		b.WriteString("\tvar input Input\n\n")

		// Auto-detect piped stdin (when stdin is not a TTY and no explicit arg)
		b.WriteString("\t// 1. Read piped JSON from stdin if available\n")
		b.WriteString("\tvar baseJSON []byte\n")
		b.WriteString("\tif len(args) > 0 {\n")
		b.WriteString("\t\tif args[0] == \"-\" {\n")
		b.WriteString("\t\t\tvar err error\n")
		b.WriteString("\t\t\tbaseJSON, err = io.ReadAll(os.Stdin)\n")
		b.WriteString("\t\t\tif err != nil {\n")
		b.WriteString("\t\t\t\tfmt.Fprintf(os.Stderr, \"Error reading stdin: %%v\\n\", err)\n")
		b.WriteString("\t\t\t\tos.Exit(1)\n")
		b.WriteString("\t\t\t}\n")
		b.WriteString("\t\t} else {\n")
		b.WriteString("\t\t\tbaseJSON = []byte(args[0])\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t} else {\n")
		b.WriteString("\t\t// Auto-detect piped stdin\n")
		b.WriteString("\t\tfi, _ := os.Stdin.Stat()\n")
		b.WriteString("\t\tif (fi.Mode() & os.ModeCharDevice) == 0 {\n")
		b.WriteString("\t\t\tbaseJSON, _ = io.ReadAll(os.Stdin)\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n\n")

		b.WriteString("\t// 2. Parse base JSON if we have it\n")
		b.WriteString("\tif len(baseJSON) > 0 {\n")
		b.WriteString("\t\tif err := json.Unmarshal(baseJSON, &input); err != nil {\n")
		b.WriteString("\t\t\tfmt.Fprintf(os.Stderr, \"Error parsing JSON: %%v\\n\", err)\n")
		b.WriteString("\t\t\tos.Exit(1)\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n\n")

		b.WriteString("\t// 3. Apply flag overrides (flags always win over piped JSON)\n")
		inputSchema := proj.Input.Parsed.(*schema.ParsedSchema)
		for name, prop := range inputSchema.Properties {
			if !schema.IsPrimitiveType(prop.Type) {
				continue
			}
			camelName := toCamelCase(name)
			pascalName := toPascalCase(name)
			switch prop.Type {
			case "string":
				b.WriteString(fmt.Sprintf("\tif %s != \"\" {\n\t\tinput.%s = %s\n\t}\n", camelName, pascalName, camelName))
			case "boolean":
				b.WriteString(fmt.Sprintf("\tif %s {\n\t\tinput.%s = %s\n\t}\n", camelName, pascalName, camelName))
			case "integer", "number":
				b.WriteString(fmt.Sprintf("\tif %s != 0 {\n\t\tinput.%s = %s\n\t}\n", camelName, pascalName, camelName))
			}
		}

		b.WriteString("\n\treturn input\n")
	} else {
		b.WriteString("string {\n")
		b.WriteString("\tif len(args) > 0 {\n")
		b.WriteString("\t\treturn args[0]\n")
		b.WriteString("\t}\n")
		b.WriteString("\t// Auto-detect piped stdin for conversational agents\n")
		b.WriteString("\tfi, _ := os.Stdin.Stat()\n")
		b.WriteString("\tif (fi.Mode() & os.ModeCharDevice) == 0 {\n")
		b.WriteString("\t\tdata, _ := io.ReadAll(os.Stdin)\n")
		b.WriteString("\t\tif len(data) > 0 {\n")
		b.WriteString("\t\t\treturn strings.TrimSpace(string(data))\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn jsonInput\n")
	}
	b.WriteString("}\n")

	return b.String(), nil
}

func generateFlagCode(flag schema.FlagDef) string {
	var b strings.Builder
	flagName := strings.TrimPrefix(flag.Name, "--")
	varName := toCamelCase(flag.PropertyName)

	switch flag.Type {
	case "boolean":
		defVal := false
		if v, ok := flag.DefaultValue.(bool); ok {
			defVal = v
		}
		b.WriteString(fmt.Sprintf("\trootCmd.Flags().BoolVar(&%s, \"%s\", %v, \"%s\")\n",
			varName, flagName, defVal, escapeString(flag.Description)))
	case "integer":
		defVal := 0
		if v, ok := flag.DefaultValue.(float64); ok {
			defVal = int(v)
		}
		b.WriteString(fmt.Sprintf("\trootCmd.Flags().IntVar(&%s, \"%s\", %d, \"%s\")\n",
			varName, flagName, defVal, escapeString(flag.Description)))
	case "number":
		defVal := 0.0
		if v, ok := flag.DefaultValue.(float64); ok {
			defVal = v
		}
		b.WriteString(fmt.Sprintf("\trootCmd.Flags().Float64Var(&%s, \"%s\", %v, \"%s\")\n",
			varName, flagName, defVal, escapeString(flag.Description)))
	default:
		defVal := ""
		if v, ok := flag.DefaultValue.(string); ok {
			defVal = v
		}
		b.WriteString(fmt.Sprintf("\trootCmd.Flags().StringVar(&%s, \"%s\", \"%s\", \"%s\")\n",
			varName, flagName, defVal, escapeString(flag.Description)))
	}

	return b.String()
}

func generateFreeformHelpers(agentInteractive bool) string {
	var b strings.Builder

	b.WriteString(`func isTerminal() bool {
	fi, err := os.Stdout.Stat()
	if err != nil {
		return false
	}
	return (fi.Mode() & os.ModeCharDevice) != 0
}

`)
	b.WriteString(fmt.Sprintf(`func shouldShowForm() bool {
	if nonInteractive {
		return false
	}
	if !%v {
		return false
	}
	return isTerminal()
}

`, agentInteractive))

	return b.String()
}

func generateWorkingInteractiveHelpers(agentInteractive bool, inputSchema *schema.ParsedSchema, inputOrder []string) string {
	var b strings.Builder

	// isTerminal
	b.WriteString(`func isTerminal() bool {
	fi, err := os.Stdout.Stat()
	if err != nil {
		return false
	}
	return (fi.Mode() & os.ModeCharDevice) != 0
}

`)

	// shouldShowForm
	b.WriteString(fmt.Sprintf(`func shouldShowForm() bool {
	if nonInteractive {
		return false
	}
	if !%v {
		return false
	}
	return isTerminal()
}

`, agentInteractive))

	// getMissingRequiredFields - check actual flag variable values
	b.WriteString("func getMissingRequiredFields() []string {\n")
	b.WriteString("\tvar missing []string\n")
	for _, req := range inputSchema.Required {
		prop, ok := inputSchema.Properties[req]
		if !ok || !schema.IsPrimitiveType(prop.Type) {
			continue
		}
		camelName := toCamelCase(req)
		switch prop.Type {
		case "string":
			b.WriteString(fmt.Sprintf("\tif %s == \"\" {\n\t\tmissing = append(missing, %q)\n\t}\n", camelName, req))
		case "integer":
			// Only consider missing if no default and value is 0
			if prop.Default == nil {
				b.WriteString(fmt.Sprintf("\tif %s == 0 {\n\t\tmissing = append(missing, %q)\n\t}\n", camelName, req))
			}
		case "number":
			if prop.Default == nil {
				b.WriteString(fmt.Sprintf("\tif %s == 0 {\n\t\tmissing = append(missing, %q)\n\t}\n", camelName, req))
			}
		case "boolean":
			// booleans are never "missing" - false is a valid value
		}
	}
	b.WriteString("\treturn missing\n}\n\n")

	// formatMissingArgs
	b.WriteString(`func formatMissingArgs(missing []string) string {
	var b strings.Builder
	b.WriteString("Missing required arguments:\n\n")
	for _, name := range missing {
		info := propertyInfo[name]
		desc := info.desc
		if desc == "" {
			desc = name
		}
		b.WriteString(fmt.Sprintf("  --%-15s %s\n", name, desc))
	}
	b.WriteString("\nRun with --help for usage information.")
	return b.String()
}

`)

	// collectPrefillValues - collect current flag values into a map
	b.WriteString("func collectPrefillValues() map[string]any {\n")
	b.WriteString("\tvalues := map[string]any{}\n")
	for name, prop := range inputSchema.Properties {
		if !schema.IsPrimitiveType(prop.Type) {
			continue
		}
		camelName := toCamelCase(name)
		switch prop.Type {
		case "string":
			b.WriteString(fmt.Sprintf("\tif %s != \"\" {\n\t\tvalues[%q] = %s\n\t}\n", camelName, name, camelName))
		case "integer":
			b.WriteString(fmt.Sprintf("\tif %s != 0 {\n\t\tvalues[%q] = %s\n\t}\n", camelName, name, camelName))
		case "number":
			b.WriteString(fmt.Sprintf("\tif %s != 0 {\n\t\tvalues[%q] = %s\n\t}\n", camelName, name, camelName))
		case "boolean":
			b.WriteString(fmt.Sprintf("\tif %s {\n\t\tvalues[%q] = %s\n\t}\n", camelName, name, camelName))
		}
	}
	b.WriteString("\treturn values\n}\n\n")

	// createForm - build actual huh form fields from schema
	b.WriteString("func createForm(prefill map[string]any) *huh.Form {\n")
	b.WriteString("\tvar fields []huh.Field\n\n")

	// Determine field order
	orderedFields := inputOrder
	if len(orderedFields) == 0 {
		for name, prop := range inputSchema.Properties {
			if schema.IsPrimitiveType(prop.Type) || len(prop.Enum) > 0 {
				orderedFields = append(orderedFields, name)
			}
		}
	}

	for _, name := range orderedFields {
		prop, ok := inputSchema.Properties[name]
		if !ok {
			continue
		}

		required := false
		for _, r := range inputSchema.Required {
			if r == name {
				required = true
				break
			}
		}

		title := prop.Description
		if title == "" {
			title = name
		}

		switch {
		case len(prop.Enum) > 0 && prop.Type == "string":
			b.WriteString(fmt.Sprintf("\t// Select field: %s\n", name))
			b.WriteString(fmt.Sprintf("\t%sVal := \"\"\n", name))
			b.WriteString(fmt.Sprintf("\tif v, ok := prefill[%q].(string); ok {\n\t\t%sVal = v\n\t}\n", name, name))
			b.WriteString(fmt.Sprintf("\tfields = append(fields, huh.NewSelect[string]().\n"))
			b.WriteString(fmt.Sprintf("\t\tTitle(%q).\n", title))
			b.WriteString(fmt.Sprintf("\t\tKey(%q).\n", name))
			b.WriteString("\t\tOptions(\n")
			for _, opt := range prop.Enum {
				b.WriteString(fmt.Sprintf("\t\t\thuh.NewOption(%q, %q),\n", opt, opt))
			}
			b.WriteString(fmt.Sprintf("\t\t).\n\t\tValue(&%sVal))\n\n", name))

		case prop.Type == "boolean":
			defVal := "false"
			if d, ok := prop.Default.(bool); ok && d {
				defVal = "true"
			}
			b.WriteString(fmt.Sprintf("\t%sVal := %s\n", name, defVal))
			b.WriteString(fmt.Sprintf("\tif v, ok := prefill[%q].(bool); ok {\n\t\t%sVal = v\n\t}\n", name, name))
			b.WriteString(fmt.Sprintf("\tfields = append(fields, huh.NewConfirm().\n"))
			b.WriteString(fmt.Sprintf("\t\tTitle(%q).\n", title))
			b.WriteString(fmt.Sprintf("\t\tKey(%q).\n", name))
			b.WriteString(fmt.Sprintf("\t\tValue(&%sVal))\n\n", name))

		case prop.Type == "string":
			defVal := ""
			if d, ok := prop.Default.(string); ok {
				defVal = d
			}
			b.WriteString(fmt.Sprintf("\t%sVal := %q\n", name, defVal))
			b.WriteString(fmt.Sprintf("\tif v, ok := prefill[%q].(string); ok {\n\t\t%sVal = v\n\t}\n", name, name))
			inputField := fmt.Sprintf("\tfields = append(fields, huh.NewInput().\n\t\tTitle(%q).\n\t\tKey(%q).\n\t\tValue(&%sVal)", title, name, name)
			if required {
				inputField += ".\n\t\tValidate(huh.ValidateNotEmpty())"
			}
			b.WriteString(inputField + ")\n\n")

		case prop.Type == "integer" || prop.Type == "number":
			defVal := ""
			if d, ok := prop.Default.(float64); ok {
				defVal = fmt.Sprintf("%v", d)
			}
			b.WriteString(fmt.Sprintf("\t%sVal := %q\n", name, defVal))
			b.WriteString(fmt.Sprintf("\tif v, ok := prefill[%q].(int); ok {\n\t\t%sVal = fmt.Sprintf(\"%%d\", v)\n\t}\n", name, name))
			b.WriteString(fmt.Sprintf("\tif v, ok := prefill[%q].(float64); ok {\n\t\t%sVal = fmt.Sprintf(\"%%v\", v)\n\t}\n", name, name))
			b.WriteString(fmt.Sprintf("\tfields = append(fields, huh.NewInput().\n\t\tTitle(%q).\n\t\tKey(%q).\n\t\tValue(&%sVal))\n\n", title, name, name))
		}
	}

	// Add remaining properties not in order
	b.WriteString("\t// Remaining properties not in explicit order\n")
	for name, prop := range inputSchema.Properties {
		inOrder := false
		for _, o := range orderedFields {
			if o == name {
				inOrder = true
				break
			}
		}
		if inOrder {
			continue
		}
		if !schema.IsPrimitiveType(prop.Type) && len(prop.Enum) == 0 {
			continue
		}

		title := prop.Description
		if title == "" {
			title = name
		}

		if prop.Type == "string" && len(prop.Enum) == 0 {
			b.WriteString(fmt.Sprintf("\t%sVal := \"\"\n", name))
			b.WriteString(fmt.Sprintf("\tif v, ok := prefill[%q].(string); ok {\n\t\t%sVal = v\n\t}\n", name, name))
			b.WriteString(fmt.Sprintf("\tfields = append(fields, huh.NewInput().Title(%q).Key(%q).Value(&%sVal))\n\n", title, name, name))
		}
	}

	b.WriteString("\tif len(fields) == 0 {\n")
	b.WriteString("\t\treturn huh.NewForm(huh.NewGroup())\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn huh.NewForm(huh.NewGroup(fields...))\n")
	b.WriteString("}\n\n")

	// applyFormResults - read form values back into flag variables
	b.WriteString("func applyFormResults(form *huh.Form) {\n")
	for name, prop := range inputSchema.Properties {
		if !schema.IsPrimitiveType(prop.Type) {
			continue
		}
		camelName := toCamelCase(name)
		switch prop.Type {
		case "string":
			b.WriteString(fmt.Sprintf("\tif v := form.GetString(%q); v != \"\" {\n\t\t%s = v\n\t}\n", name, camelName))
		case "boolean":
			b.WriteString(fmt.Sprintf("\tif v := form.Get(%q); v != nil {\n\t\tif b, ok := v.(bool); ok {\n\t\t\t%s = b\n\t\t}\n\t}\n", name, camelName))
		case "integer":
			b.WriteString(fmt.Sprintf("\tif v := form.GetString(%q); v != \"\" {\n\t\tif i, err := strconv.Atoi(v); err == nil {\n\t\t\t%s = i\n\t\t}\n\t}\n", name, camelName))
		case "number":
			b.WriteString(fmt.Sprintf("\tif v := form.GetString(%q); v != \"\" {\n\t\tif f, err := strconv.ParseFloat(v, 64); err == nil {\n\t\t\t%s = f\n\t\t}\n\t}\n", name, camelName))
		}
	}
	b.WriteString("}\n\n")

	return b.String()
}
