package generate

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/charmbracelet/ayo/internal/project"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

func GenerateEmbeds(proj *project.Project, pkgName string) (string, error) {
	var b strings.Builder

	b.WriteString("// Code generated by ayo. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkgName))

	b.WriteString("import (\n")
	if len(proj.Skills) > 0 {
		b.WriteString("\t\"embed\"\n")
	} else {
		b.WriteString("\t_ \"embed\"\n")
	}
	if proj.Prompt != nil {
		b.WriteString("\t\"bytes\"\n")
		b.WriteString("\t\"fmt\"\n")
		b.WriteString("\t\"os\"\n")
		b.WriteString("\t\"strings\"\n")
		b.WriteString("\t\"text/template\"\n")
	}
	if proj.Input != nil && proj.Prompt == nil {
		b.WriteString("\t\"encoding/json\"\n")
	}
	b.WriteString(")\n\n")

	b.WriteString("//go:embed system.md\n")
	b.WriteString("var systemMessage string\n\n")

	if proj.Prompt != nil {
		b.WriteString("//go:embed prompt.tmpl\n")
		b.WriteString("var promptTemplate string\n\n")
	}

	if len(proj.Skills) > 0 {
		b.WriteString("// Skill files embedded in the binary.\n")
		for _, skill := range proj.Skills {
			safeName := toSafeIdentifier(skill.Name)
			b.WriteString(fmt.Sprintf("//go:embed skills/%s/*\n", skill.Name))
			b.WriteString(fmt.Sprintf("var skill%s embed.FS\n\n", safeName))
		}
	}

	if len(proj.Hooks) > 0 {
		b.WriteString("// Hook files embedded in the binary.\n")
		for hookType := range proj.Hooks {
			safeName := toSafeIdentifier(string(hookType))
			b.WriteString(fmt.Sprintf("//go:embed hooks/%s\n", hookType))
			b.WriteString(fmt.Sprintf("var hook%s []byte\n\n", safeName))
		}
	}

	// Generate skills catalog when skills exist
	if len(proj.Skills) > 0 {
		b.WriteString("// skillsCatalog lists all available skills for the agent.\n")
		b.WriteString("var skillsCatalog = `## Available Skills\n\n")
		for _, skill := range proj.Skills {
			b.WriteString(fmt.Sprintf("### %s\n", skill.Name))
			if skill.Description != "" {
				b.WriteString(skill.Description + "\n")
			}
			b.WriteString(fmt.Sprintf("embedded://%s/SKILL.md\n\n", skill.Path))
		}
		b.WriteString("`\n\n")
	}

	b.WriteString("// getSystemMessage returns the system message for the agent.\n")
	b.WriteString("func getSystemMessage() string {\n")
	if len(proj.Skills) > 0 {
		b.WriteString("\treturn systemMessage + skillsCatalog\n")
	} else {
		b.WriteString("\treturn systemMessage\n")
	}
	b.WriteString("}\n")

	if proj.Prompt != nil {
		// Generate template functions
		b.WriteString("// templateFuncs contains custom functions available in templates.\n")
		b.WriteString("var templateFuncs = template.FuncMap{\n")
		b.WriteString("\t\"json\":  marshalJSONFunc,\n")
		b.WriteString("\t\"file\": readFileFunc,\n")
		b.WriteString("\t\"env\":  os.Getenv,\n")
		b.WriteString("\t\"upper\": strings.ToUpper,\n")
		b.WriteString("\t\"lower\": strings.ToLower,\n")
		b.WriteString("\t\"title\": strings.Title,\n")
		b.WriteString("\t\"trim\":  strings.TrimSpace,\n")
		b.WriteString("}\n\n")

		b.WriteString("// marshalJSONFunc converts a value to a JSON string.\n")
		b.WriteString("func marshalJSONFunc(v any) (string, error) {\n")
		b.WriteString("\tvar buf bytes.Buffer\n")
		b.WriteString("\tif err := encodeJSON(&buf, v, 0); err != nil {\n")
		b.WriteString("\t\treturn \"\", err\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn buf.String(), nil\n")
		b.WriteString("}\n\n")

		b.WriteString("// readFileFunc reads the contents of a file.\n")
		b.WriteString("func readFileFunc(path string) (string, error) {\n")
		b.WriteString("\tdata, err := os.ReadFile(path)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\treturn \"\", fmt.Errorf(\"reading file %s: %w\", path, err)\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn string(data), nil\n")
		b.WriteString("}\n\n")

		b.WriteString("// encodeJSON encodes a value to JSON with indentation.\n")
		b.WriteString("func encodeJSON(buf *bytes.Buffer, v any, indent int) error {\n")
		b.WriteString("\tswitch val := v.(type) {\n")
		b.WriteString("\tcase string:\n")
		b.WriteString("\t\tbuf.WriteString(fmt.Sprintf(\"%q\", val))\n")
		b.WriteString("\tcase int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64, float32, float64, bool:\n")
		b.WriteString("\t\tbuf.WriteString(fmt.Sprintf(\"%v\", val))\n")
		b.WriteString("\tcase nil:\n")
		b.WriteString("\t\tbuf.WriteString(\"null\")\n")
		b.WriteString("\tcase map[string]any:\n")
		b.WriteString("\t\tencodeJSONMap(buf, val, indent)\n")
		b.WriteString("\tcase []any:\n")
		b.WriteString("\t\tencodeJSONSlice(buf, val, indent)\n")
		b.WriteString("\tdefault:\n")
		b.WriteString("\t\tbuf.WriteString(fmt.Sprintf(\"%q\", fmt.Sprintf(\"%v\", val)))\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn nil\n")
		b.WriteString("}\n\n")

		b.WriteString("// encodeJSONMap encodes a map to JSON.\n")
		b.WriteString("func encodeJSONMap(buf *bytes.Buffer, m map[string]any, indent int) {\n")
		b.WriteString("\tbuf.WriteString(\"{\\n\")\n")
		b.WriteString("\tfirst := true\n")
		b.WriteString("\tfor k, v := range m {\n")
		b.WriteString("\t\tif !first {\n")
		b.WriteString("\t\t\tbuf.WriteString(\",\\n\")\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t\tfirst = false\n")
		b.WriteString("\t\tbuf.WriteString(strings.Repeat(\"  \", indent+1))\n")
		b.WriteString("\t\tbuf.WriteString(fmt.Sprintf(\"%q: \", k))\n")
		b.WriteString("\t\tencodeJSON(buf, v, indent+1)\n")
		b.WriteString("\t}\n")
		b.WriteString("\tbuf.WriteString(\"\\n\")\n")
		b.WriteString("\tbuf.WriteString(strings.Repeat(\"  \", indent))\n")
		b.WriteString("\tbuf.WriteString(\"}\")\n")
		b.WriteString("}\n\n")

		b.WriteString("// encodeJSONSlice encodes a slice to JSON.\n")
		b.WriteString("func encodeJSONSlice(buf *bytes.Buffer, s []any, indent int) {\n")
		b.WriteString("\tif len(s) == 0 {\n")
		b.WriteString("\t\tbuf.WriteString(\"[]\")\n")
		b.WriteString("\t\treturn\n")
		b.WriteString("\t}\n")
		b.WriteString("\tbuf.WriteString(\"[\\n\")\n")
		b.WriteString("\tfor i, v := range s {\n")
		b.WriteString("\t\tif i > 0 {\n")
		b.WriteString("\t\t\tbuf.WriteString(\",\\n\")\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t\tbuf.WriteString(strings.Repeat(\"  \", indent+1))\n")
		b.WriteString("\t\tencodeJSON(buf, v, indent+1)\n")
		b.WriteString("\t}\n")
		b.WriteString("\tbuf.WriteString(\"\\n\")\n")
		b.WriteString("\tbuf.WriteString(strings.Repeat(\"  \", indent))\n")
		b.WriteString("\tbuf.WriteString(\"]\")\n")
		b.WriteString("}\n\n")

		// Generate renderPrompt function
		b.WriteString("\n// renderPrompt renders the prompt template with the given input.\n")
		if proj.Input != nil {
			b.WriteString("func renderPrompt(input Input) string {\n")
		} else {
			b.WriteString("func renderPrompt(input string) string {\n")
		}
		b.WriteString("\ttmpl, err := template.New(\"prompt\").Funcs(templateFuncs).Parse(promptTemplate)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\treturn promptTemplate // fallback to raw template on parse error\n")
		b.WriteString("\t}\n\n")
		b.WriteString("\tvar buf bytes.Buffer\n")
		if proj.Input != nil {
			b.WriteString("\tdata := map[string]any{\n")
			b.WriteString("\t\t\"input\": input,\n")
			b.WriteString("\t}\n")
			b.WriteString("\tif err := tmpl.Execute(&buf, data); err != nil {\n")
		} else {
			b.WriteString("\tif err := tmpl.Execute(&buf, map[string]any{\"input\": input}); err != nil {\n")
		}
		b.WriteString("\t\treturn promptTemplate // fallback to raw template on execute error\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn buf.String()\n")
		b.WriteString("}\n")
	} else {
		b.WriteString("\n// renderPrompt returns the input as-is (no template).\n")
		if proj.Input != nil {
			b.WriteString("func renderPrompt(input Input) string {\n")
			b.WriteString("\tdata, _ := json.Marshal(input)\n")
			b.WriteString("\treturn string(data)\n")
		} else {
			b.WriteString("func renderPrompt(input string) string {\n")
			b.WriteString("\treturn input\n")
		}
		b.WriteString("}\n")
	}

	return b.String(), nil
}

func toSafeIdentifier(s string) string {
	s = strings.ReplaceAll(s, "-", "_")
	s = strings.ReplaceAll(s, ".", "_")
	parts := strings.Split(s, "_")
	for i, part := range parts {
		parts[i] = cases.Title(language.English).String(part)
	}
	return strings.Join(parts, "")
}

func GenerateGoMod(proj *project.Project) string {
	return fmt.Sprintf(`module %s

go 1.22

require (
	github.com/BurntSushi/toml v1.6.0
	github.com/charmbracelet/bubbles v0.20.0
	github.com/charmbracelet/bubbletea v1.3.4
	github.com/charmbracelet/lipgloss v1.1.0
	github.com/spf13/cobra v1.10.2
	charm.land/fantasy v0.0.0
)

replace charm.land/fantasy => ./fantasy
`, filepath.Base(proj.Path))
}
