package generate

import (
	"strings"
	"testing"

	"github.com/ayo-ooo/ayo/internal/project"
	"github.com/ayo-ooo/ayo/internal/testutil"
)

func TestNewGenerator(t *testing.T) {
	g := NewGenerator()
	if g == nil {
		t.Error("NewGenerator() should not return nil")
	}
}

func TestGenerator_Generate(t *testing.T) {
	parsedInput := mustParseSchema(testutil.ValidInputSchema())
	prompt := "Test prompt"

	proj := &project.Project{
		Config: project.AgentConfig{
			Name:        "test-agent",
			Description: "A test agent",
		},
		System: "You are a helpful assistant.",
		Prompt: &prompt,
		Input: &project.Schema{
			Content: []byte(testutil.ValidInputSchema()),
			Parsed:  parsedInput,
		},
	}

	g := NewGenerator()
	files, err := g.Generate(proj, "main")
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	expectedFiles := []string{"cli.go", "agent.go", "embed.go", "tui.go", "main.go"}
	for _, expected := range expectedFiles {
		if _, ok := files[expected]; !ok {
			t.Errorf("Generate() missing file %q", expected)
		}
	}

	for name, content := range files {
		if content == "" {
			t.Errorf("Generate() file %q is empty", name)
		}
		if !strings.Contains(content, "package main") {
			t.Errorf("Generate() file %q should contain 'package main'", name)
		}
	}
}

func TestGenerator_Generate_NoInput(t *testing.T) {
	proj := &project.Project{
		Config: project.AgentConfig{
			Name:        "no-input-agent",
			Description: "No input agent",
		},
		System: "You are a helpful assistant.",
	}

	g := NewGenerator()
	files, err := g.Generate(proj, "cmd")
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	if _, ok := files["cli.go"]; !ok {
		t.Error("Generate() should include cli.go even without input")
	}

	if !strings.Contains(files["cli.go"], "package cmd") {
		t.Error("Generate() should use specified package name")
	}
}

func TestGenerator_Generate_WithSkills(t *testing.T) {
	parsedInput := mustParseSchema(testutil.ValidInputSchema())

	proj := &project.Project{
		Config: project.AgentConfig{
			Name:        "skillful-agent",
			Description: "An agent with skills",
		},
		System: "You are a helpful assistant.",
		Input: &project.Schema{
			Content: []byte(testutil.ValidInputSchema()),
			Parsed:  parsedInput,
		},
		Skills: []project.Skill{
			{Name: "search", Path: "skills/search", Description: "Search skill"},
		},
	}

	g := NewGenerator()
	files, err := g.Generate(proj, "main")
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	if !strings.Contains(files["embed.go"], "skillSearch") {
		t.Error("Generate() should include skill embeds")
	}
}

func TestGenerateMain(t *testing.T) {
	proj := &project.Project{
		Config: project.AgentConfig{
			Name: "test-main",
		},
	}

	g := NewGenerator()
	code, err := g.GenerateMain(proj)
	if err != nil {
		t.Fatalf("GenerateMain() error = %v", err)
	}

	if !strings.Contains(code, "package main") {
		t.Error("GenerateMain() should contain 'package main'")
	}

	if !strings.Contains(code, "func main()") {
		t.Error("GenerateMain() should contain main function")
	}

	if !strings.Contains(code, "Execute()") {
		t.Error("GenerateMain() should call Execute()")
	}

	if !strings.Contains(code, "os.Exit(1)") {
		t.Error("GenerateMain() should handle errors with os.Exit(1)")
	}
}

func TestGenerateMain_GeneratedHeader(t *testing.T) {
	proj := &project.Project{
		Config: project.AgentConfig{
			Name: "header-test",
		},
	}

	g := NewGenerator()
	code, err := g.GenerateMain(proj)
	if err != nil {
		t.Fatalf("GenerateMain() error = %v", err)
	}

	if !strings.Contains(code, "// Code generated by ayo. DO NOT EDIT.") {
		t.Error("GenerateMain() should contain generation header")
	}
}

func TestGenerateTUI(t *testing.T) {
	proj := &project.Project{
		Config: project.AgentConfig{
			Name: "test-tui",
		},
	}

	code, err := GenerateTUI(proj, "main")
	if err != nil {
		t.Fatalf("GenerateTUI() error = %v", err)
	}

	if !strings.Contains(code, "package main") {
		t.Error("GenerateTUI() should contain 'package main'")
	}

	if !strings.Contains(code, "import") {
		t.Error("GenerateTUI() should contain imports")
	}

	if !strings.Contains(code, "bubbletea") {
		t.Error("GenerateTUI() should import bubbletea")
	}

	if !strings.Contains(code, "tuiState") {
		t.Error("GenerateTUI() should define TUI states")
	}

	if !strings.Contains(code, "catwalk") {
		t.Error("GenerateTUI() should import catwalk for model discovery")
	}
}

func TestGenerateTUI_ProviderDiscovery(t *testing.T) {
	proj := &project.Project{
		Config: project.AgentConfig{
			Name: "provider-test",
		},
	}

	code, err := GenerateTUI(proj, "main")
	if err != nil {
		t.Fatalf("GenerateTUI() error = %v", err)
	}

	// Check that it uses catwalk for dynamic provider discovery
	if !strings.Contains(code, "getProviders") {
		t.Error("GenerateTUI() should define getProviders function")
	}

	if !strings.Contains(code, "embedded.GetAll()") {
		t.Error("GenerateTUI() should use embedded providers as fallback")
	}

	// Check for API key detection
	if !strings.Contains(code, "hasAPIKey") {
		t.Error("GenerateTUI() should define hasAPIKey function")
	}

	if !strings.Contains(code, "getAPIKeyEnv") {
		t.Error("GenerateTUI() should define getAPIKeyEnv function")
	}
}

func TestGenerateTUI_TUIStates(t *testing.T) {
	proj := &project.Project{
		Config: project.AgentConfig{
			Name: "state-test",
		},
	}

	code, err := GenerateTUI(proj, "main")
	if err != nil {
		t.Fatalf("GenerateTUI() error = %v", err)
	}

	states := []string{"stateProviderSelect", "stateModelSelect", "stateConfirm"}
	for _, state := range states {
		if !strings.Contains(code, state) {
			t.Errorf("GenerateTUI() should define state %q", state)
		}
	}
}

func TestGenerateTUI_GeneratedHeader(t *testing.T) {
	proj := &project.Project{
		Config: project.AgentConfig{
			Name: "header-test",
		},
	}

	code, err := GenerateTUI(proj, "main")
	if err != nil {
		t.Fatalf("GenerateTUI() error = %v", err)
	}

	if !strings.Contains(code, "// Code generated by ayo. DO NOT EDIT.") {
		t.Error("GenerateTUI() should contain generation header")
	}
}

func TestGenerateEmbeds_Basic(t *testing.T) {
	proj := &project.Project{
		Config: project.AgentConfig{
			Name: "embed-test",
		},
		System: "You are helpful.",
	}

	code, err := GenerateEmbeds(proj, "main")
	if err != nil {
		t.Fatalf("GenerateEmbeds() error = %v", err)
	}

	if !strings.Contains(code, "package main") {
		t.Error("GenerateEmbeds() should contain 'package main'")
	}

	if !strings.Contains(code, "//go:embed system.md") {
		t.Error("GenerateEmbeds() should embed system.md")
	}

	if !strings.Contains(code, "var systemMessage string") {
		t.Error("GenerateEmbeds() should define systemMessage variable")
	}
}

func TestGenerateEmbeds_WithPrompt(t *testing.T) {
	prompt := "Hello {{.Name}}"
	proj := &project.Project{
		Config: project.AgentConfig{
			Name: "prompt-embed-test",
		},
		System: "You are helpful.",
		Prompt: &prompt,
	}

	code, err := GenerateEmbeds(proj, "main")
	if err != nil {
		t.Fatalf("GenerateEmbeds() error = %v", err)
	}

	if !strings.Contains(code, "//go:embed prompt.tmpl") {
		t.Error("GenerateEmbeds() should embed prompt.tmpl when prompt exists")
	}

	if !strings.Contains(code, "var promptTemplate string") {
		t.Error("GenerateEmbeds() should define promptTemplate variable")
	}

	if !strings.Contains(code, "text/template") {
		t.Error("GenerateEmbeds() should import text/template when prompt exists")
	}
}

func TestGenerateEmbeds_WithSkills(t *testing.T) {
	proj := &project.Project{
		Config: project.AgentConfig{
			Name: "skill-embed-test",
		},
		System: "You are helpful.",
		Skills: []project.Skill{
			{Name: "search", Path: "skills/search", Description: "Search"},
			{Name: "code-gen", Path: "skills/code-gen", Description: "Code generation"},
		},
	}

	code, err := GenerateEmbeds(proj, "main")
	if err != nil {
		t.Fatalf("GenerateEmbeds() error = %v", err)
	}

	if !strings.Contains(code, "skillSearch") {
		t.Error("GenerateEmbeds() should embed search skill")
	}

	if !strings.Contains(code, "skillCodeGen") {
		t.Error("GenerateEmbeds() should embed code-gen skill with safe identifier")
	}

	if !strings.Contains(code, "embed.FS") {
		t.Error("GenerateEmbeds() should use embed.FS for skills")
	}
}

func TestGenerateEmbeds_WithInput(t *testing.T) {
	parsedInput := mustParseSchema(testutil.ValidInputSchema())
	proj := &project.Project{
		Config: project.AgentConfig{
			Name: "input-embed-test",
		},
		System: "You are helpful.",
		Input: &project.Schema{
			Content: []byte(testutil.ValidInputSchema()),
			Parsed:  parsedInput,
		},
	}

	code, err := GenerateEmbeds(proj, "main")
	if err != nil {
		t.Fatalf("GenerateEmbeds() error = %v", err)
	}

	if !strings.Contains(code, "encoding/json") {
		t.Error("GenerateEmbeds() should import encoding/json when input exists")
	}
}

func TestGenerateEmbeds_GeneratedHeader(t *testing.T) {
	proj := &project.Project{
		Config: project.AgentConfig{
			Name: "header-test",
		},
		System: "You are helpful.",
	}

	code, err := GenerateEmbeds(proj, "main")
	if err != nil {
		t.Fatalf("GenerateEmbeds() error = %v", err)
	}

	if !strings.Contains(code, "// Code generated by ayo. DO NOT EDIT.") {
		t.Error("GenerateEmbeds() should contain generation header")
	}
}

func TestGenerateGoMod_Dependencies(t *testing.T) {
	proj := &project.Project{
		Path: "/path/to/gomod-test",
		Config: project.AgentConfig{
			Name:    "gomod-test",
			Version: "1.0.0",
		},
	}

	code := GenerateGoMod(proj)

	if !strings.Contains(code, "module gomod-test") {
		t.Error("GenerateGoMod() should contain module name")
	}

	if !strings.Contains(code, "go ") {
		t.Error("GenerateGoMod() should contain go version")
	}

	if !strings.Contains(code, "github.com/spf13/cobra") {
		t.Error("GenerateGoMod() should contain cobra dependency")
	}

	if !strings.Contains(code, "charm.land/fantasy") {
		t.Error("GenerateGoMod() should contain fantasy dependency")
	}
}

func TestGenerateGoMod_WithProjectPath(t *testing.T) {
	proj := &project.Project{
		Path: "/some/path/my-agent",
		Config: project.AgentConfig{
			Name:    "my-agent",
			Version: "1.0.0",
		},
	}

	code := GenerateGoMod(proj)

	if !strings.Contains(code, "module my-agent") {
		t.Error("GenerateGoMod() should use basename of path as module name")
	}
}
