package generate

import (
	"fmt"
	"strings"

	"github.com/ayo-ooo/ayo/internal/project"
)

// GenerateHooks generates the hook runner code for the generated agent
func GenerateHooks(proj *project.Project, pkgName string) (string, error) {
	var b strings.Builder

	b.WriteString("// Code generated by ayo. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkgName))

	b.WriteString("import (\n")
	b.WriteString("\t\"bytes\"\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"log\"\n")
	b.WriteString("\t\"os\"\n")
	b.WriteString("\t\"os/exec\"\n")
	b.WriteString("\t\"path/filepath\"\n")
	b.WriteString("\t\"time\"\n")
	b.WriteString(")\n\n")

	// Hook type constants
	b.WriteString("// HookType represents a hook event type\n")
	b.WriteString("type HookType string\n\n")
	b.WriteString("const (\n")
	b.WriteString("\tHookAgentStart  HookType = \"agent-start\"\n")
	b.WriteString("\tHookAgentFinish HookType = \"agent-finish\"\n")
	b.WriteString("\tHookAgentError  HookType = \"agent-error\"\n")
	b.WriteString("\tHookStepStart   HookType = \"step-start\"\n")
	b.WriteString("\tHookStepFinish  HookType = \"step-finish\"\n")
	b.WriteString("\tHookTextStart   HookType = \"text-start\"\n")
	b.WriteString("\tHookTextDelta   HookType = \"text-delta\"\n")
	b.WriteString("\tHookTextEnd     HookType = \"text-end\"\n")
	b.WriteString("\tHookToolCall    HookType = \"tool-call\"\n")
	b.WriteString("\tHookToolResult  HookType = \"tool-result\"\n")
	b.WriteString(")\n\n")

	// Hook runner struct
	b.WriteString("// HookRunner executes hooks in order (embedded then user)\n")
	b.WriteString("type HookRunner struct {\n")
	b.WriteString("\tembeddedHooks map[HookType][]byte\n")
	b.WriteString("\tuserHooks     map[HookType]string\n")
	b.WriteString("\ttempDir       string\n")
	b.WriteString("}\n\n")

	// NewHookRunner
	b.WriteString("// NewHookRunner creates a new hook runner\n")
	b.WriteString("func NewHookRunner(embedded map[HookType][]byte, user map[HookType]string, tempDir string) *HookRunner {\n")
	b.WriteString("\treturn &HookRunner{\n")
	b.WriteString("\t\tembeddedHooks: embedded,\n")
	b.WriteString("\t\tuserHooks:     user,\n")
	b.WriteString("\t\ttempDir:       tempDir,\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	// Run method
	b.WriteString("// Run executes hooks for the given hook type\n")
	b.WriteString("func (r *HookRunner) Run(ctx context.Context, hookType HookType, data any) error {\n")
	b.WriteString("\tpayload := serializeHookPayload(hookType, data)\n\n")
	b.WriteString("\t// 1. Run embedded hook if exists\n")
	b.WriteString("\tif embedded, ok := r.embeddedHooks[hookType]; ok {\n")
	b.WriteString("\t\tif err := r.executeEmbedded(ctx, hookType, embedded, payload); err != nil {\n")
	b.WriteString("\t\t\tlog.Printf(\"embedded hook %s failed: %v\", hookType, err)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\t// 2. Run user hook if configured\n")
	b.WriteString("\tif userPath, ok := r.userHooks[hookType]; ok {\n")
	b.WriteString("\t\tif err := r.executeUser(ctx, userPath, payload); err != nil {\n")
	b.WriteString("\t\t\tlog.Printf(\"user hook %s failed: %v\", hookType, err)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")

	// executeEmbedded
	b.WriteString("func (r *HookRunner) executeEmbedded(ctx context.Context, hookType HookType, content []byte, payload []byte) error {\n")
	b.WriteString("\ttmpFile := filepath.Join(r.tempDir, fmt.Sprintf(\"hook-%s\", hookType))\n")
	b.WriteString("\tif err := os.WriteFile(tmpFile, content, 0755); err != nil {\n")
	b.WriteString("\t\treturn fmt.Errorf(\"writing embedded hook: %w\", err)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdefer os.Remove(tmpFile)\n")
	b.WriteString("\treturn r.executeHook(ctx, tmpFile, payload)\n")
	b.WriteString("}\n\n")

	// executeUser
	b.WriteString("func (r *HookRunner) executeUser(ctx context.Context, hookPath string, payload []byte) error {\n")
	b.WriteString("\treturn r.executeHook(ctx, hookPath, payload)\n")
	b.WriteString("}\n\n")

	// executeHook
	b.WriteString("func (r *HookRunner) executeHook(ctx context.Context, path string, payload []byte) error {\n")
	b.WriteString("\tcmd := exec.CommandContext(ctx, path)\n")
	b.WriteString("\tcmd.Stdin = bytes.NewReader(payload)\n")
	b.WriteString("\tcmd.Stdout = os.Stderr\n")
	b.WriteString("\tcmd.Stderr = os.Stderr\n")
	b.WriteString("\tif err := cmd.Run(); err != nil {\n")
	b.WriteString("\t\treturn fmt.Errorf(\"executing hook: %w\", err)\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")

	// Payload serialization
	b.WriteString("// serializeHookPayload creates a JSON payload for the given hook type\n")
	b.WriteString("func serializeHookPayload(hookType HookType, data any) []byte {\n")
	b.WriteString("\ttimestamp := time.Now().UTC().Format(time.RFC3339)\n")
	b.WriteString("\tpayload := map[string]any{\n")
	b.WriteString("\t\t\"event\":     string(hookType),\n")
	b.WriteString("\t\t\"timestamp\": timestamp,\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif data != nil {\n")
	b.WriteString("\t\tpayload[\"data\"] = data\n")
	b.WriteString("\t}\n")
	b.WriteString("\tb, _ := json.Marshal(payload)\n")
	b.WriteString("\treturn b\n")
	b.WriteString("}\n\n")

	// Initialize hooks from embedded files and config
	b.WriteString("// initHooks initializes the hook runner with embedded and user hooks\n")
	b.WriteString("func initHooks() *HookRunner {\n")
	b.WriteString("\ttempDir, _ := os.MkdirTemp(\"\", \"ayo-hooks-*\")\n")
	b.WriteString("\tembedded := make(map[HookType][]byte)\n")
	b.WriteString("\tuser := make(map[HookType]string)\n\n")

	// Add embedded hooks
	for hookType := range proj.Hooks {
		safeName := toSafeIdentifier(string(hookType))
		b.WriteString(fmt.Sprintf("\tembedded[Hook%s] = hook%s\n", safeName, safeName))
	}

	b.WriteString("\n\t// Load user hooks from config if available\n")
	b.WriteString("\tcfg, err := loadConfig()\n")
	b.WriteString("\tif err == nil && cfg != nil {\n")
	b.WriteString("\t\t// User hooks would be loaded from config here\n")
	b.WriteString("\t\t// Currently user hooks are not implemented in config\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\treturn NewHookRunner(embedded, user, tempDir)\n")
	b.WriteString("}\n")

	return b.String(), nil
}
