package generate

import (
	"fmt"
	"strings"

	"github.com/ayo-ooo/ayo/internal/project"
)

// GenerateSession generates session management code for conversational agents.
// This includes session load/save and interactive chat mode.
func GenerateSession(proj *project.Project, pkgName string) (string, error) {
	var b strings.Builder

	agentName := proj.Config.Name

	b.WriteString("// Code generated by ayo. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkgName))

	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"os\"\n")
	b.WriteString("\t\"path/filepath\"\n")
	b.WriteString("\n")
	b.WriteString("\t\"charm.land/huh/v2\"\n")
	b.WriteString("\t\"charm.land/lipgloss/v2\"\n")
	b.WriteString(")\n\n")

	// Session directory
	b.WriteString(fmt.Sprintf("const sessionAgentName = %q\n\n", agentName))

	// Styles for chat mode
	b.WriteString("var (\n")
	b.WriteString("\tchatUserStyle = lipgloss.NewStyle().\n")
	b.WriteString("\t\tForeground(lipgloss.Color(\"#7D56F4\")).\n")
	b.WriteString("\t\tBold(true)\n\n")
	b.WriteString("\tchatAssistantStyle = lipgloss.NewStyle().\n")
	b.WriteString("\t\tForeground(lipgloss.Color(\"#04B575\"))\n\n")
	b.WriteString("\tchatDimStyle = lipgloss.NewStyle().\n")
	b.WriteString("\t\tForeground(lipgloss.Color(\"#626262\"))\n")
	b.WriteString(")\n\n")

	// sessionDir returns the session storage directory
	b.WriteString("func sessionDir() string {\n")
	b.WriteString("\thome, _ := os.UserHomeDir()\n")
	b.WriteString("\treturn filepath.Join(home, \".local\", \"share\", \"agents\", sessionAgentName, \"sessions\")\n")
	b.WriteString("}\n\n")

	// loadSession loads session history from disk
	b.WriteString("func loadSession(id string) []SessionMessage {\n")
	b.WriteString("\tpath := filepath.Join(sessionDir(), id+\".json\")\n")
	b.WriteString("\tdata, err := os.ReadFile(path)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn nil\n")
	b.WriteString("\t}\n")
	b.WriteString("\tvar messages []SessionMessage\n")
	b.WriteString("\tif err := json.Unmarshal(data, &messages); err != nil {\n")
	b.WriteString("\t\treturn nil\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn messages\n")
	b.WriteString("}\n\n")

	// saveSession persists session history to disk
	b.WriteString("func saveSession(id string, messages []SessionMessage) {\n")
	b.WriteString("\tdir := sessionDir()\n")
	b.WriteString("\tos.MkdirAll(dir, 0755)\n")
	b.WriteString("\tdata, err := json.MarshalIndent(messages, \"\", \"  \")\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn\n")
	b.WriteString("\t}\n")
	b.WriteString("\tos.WriteFile(filepath.Join(dir, id+\".json\"), data, 0644)\n")
	b.WriteString("}\n\n")

	// runChatMode launches interactive conversational TUI
	b.WriteString("func runChatMode(ctx context.Context) {\n")
	b.WriteString("\t// Generate or use provided session ID\n")
	b.WriteString("\tid := sessionID\n")
	b.WriteString("\tif id == \"\" {\n")
	b.WriteString("\t\tid = fmt.Sprintf(\"%x\", os.Getpid())\n")
	b.WriteString("\t}\n\n")

	b.WriteString("\thistory := loadSession(id)\n\n")

	b.WriteString("\tfmt.Println(chatDimStyle.Render(fmt.Sprintf(\"Chat session: %s (type 'exit' or Ctrl+C to quit)\", id)))\n")
	b.WriteString("\tfmt.Println()\n\n")

	// Print existing history
	b.WriteString("\t// Show existing conversation if resuming\n")
	b.WriteString("\tfor _, msg := range history {\n")
	b.WriteString("\t\tswitch msg.Role {\n")
	b.WriteString("\t\tcase \"user\":\n")
	b.WriteString("\t\t\tfmt.Println(chatUserStyle.Render(\"You: \") + msg.Content)\n")
	b.WriteString("\t\tcase \"assistant\":\n")
	b.WriteString("\t\t\tfmt.Println(chatAssistantStyle.Render(\"Agent: \") + msg.Content)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tfmt.Println()\n")
	b.WriteString("\t}\n\n")

	// Chat loop using huh forms for beautiful input
	b.WriteString("\tfor {\n")
	b.WriteString("\t\tvar input string\n")
	b.WriteString("\t\tform := huh.NewForm(\n")
	b.WriteString("\t\t\thuh.NewGroup(\n")
	b.WriteString("\t\t\t\thuh.NewText().\n")
	b.WriteString("\t\t\t\t\tTitle(chatUserStyle.Render(\"You\")).\n")
	b.WriteString("\t\t\t\t\tValue(&input),\n")
	b.WriteString("\t\t\t),\n")
	b.WriteString("\t\t)\n\n")

	b.WriteString("\t\tif err := form.Run(); err != nil {\n")
	b.WriteString("\t\t\tbreak // User pressed Ctrl+C\n")
	b.WriteString("\t\t}\n\n")

	b.WriteString("\t\tif input == \"\" || input == \"exit\" || input == \"quit\" {\n")
	b.WriteString("\t\t\tbreak\n")
	b.WriteString("\t\t}\n\n")

	b.WriteString("\t\tfmt.Println(chatDimStyle.Render(\"Thinking...\"))\n\n")

	b.WriteString("\t\tresult, err := executeAgentWithMessages(ctx, input, history)\n")
	b.WriteString("\t\tif err != nil {\n")
	b.WriteString("\t\t\tfmt.Fprintln(os.Stderr, chatDimStyle.Render(fmt.Sprintf(\"Error: %v\", err)))\n")
	b.WriteString("\t\t\tcontinue\n")
	b.WriteString("\t\t}\n\n")

	b.WriteString("\t\thistory = append(history, SessionMessage{Role: \"user\", Content: input})\n")
	b.WriteString("\t\thistory = append(history, SessionMessage{Role: \"assistant\", Content: result})\n")
	b.WriteString("\t\tsaveSession(id, history)\n\n")

	b.WriteString("\t\tfmt.Println()\n")
	b.WriteString("\t\tfmt.Println(chatAssistantStyle.Render(\"Agent: \") + result)\n")
	b.WriteString("\t\tfmt.Println()\n")
	b.WriteString("\t}\n\n")

	b.WriteString("\tfmt.Println(chatDimStyle.Render(\"Session saved.\"))\n")
	b.WriteString("}\n")

	return b.String(), nil
}
