package generate

import (
	"fmt"
	"strings"

	"github.com/ayo-ooo/ayo/internal/project"
)

// GenerateShell generates the sandboxed shell execution code for agents.
// Uses mvdan.cc/sh for a pure-Go POSIX shell interpreter with Go-native
// coreutils, following the pattern established by crush.
func GenerateShell(proj *project.Project, pkgName string) (string, error) {
	var b strings.Builder

	b.WriteString("// Code generated by ayo. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkgName))

	b.WriteString("import (\n")
	b.WriteString("\t\"bytes\"\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"os\"\n")
	b.WriteString("\t\"strings\"\n")
	b.WriteString("\t\"sync\"\n")
	b.WriteString("\t\"time\"\n")
	b.WriteString("\n")
	b.WriteString("\t\"charm.land/fantasy\"\n")
	b.WriteString("\t\"mvdan.cc/sh/v3/expand\"\n")
	b.WriteString("\t\"mvdan.cc/sh/v3/interp\"\n")
	b.WriteString("\t\"mvdan.cc/sh/v3/syntax\"\n")
	b.WriteString(")\n\n")

	// Shell struct
	b.WriteString("// Shell provides a sandboxed POSIX shell environment.\n")
	b.WriteString("type Shell struct {\n")
	b.WriteString("\tmu         sync.Mutex\n")
	b.WriteString("\tworkDir    string\n")
	b.WriteString("\tenv        []string\n")
	b.WriteString("\tblocked    map[string]bool\n")
	b.WriteString("\ttimeout    time.Duration\n")
	b.WriteString("\tmaxOutput  int\n")
	b.WriteString("}\n\n")

	// NewShell
	b.WriteString("// NewShell creates a sandboxed shell environment.\n")
	b.WriteString("func NewShell() *Shell {\n")
	b.WriteString("\twd, _ := os.Getwd()\n")
	b.WriteString("\treturn &Shell{\n")
	b.WriteString("\t\tworkDir:   wd,\n")
	b.WriteString("\t\tenv:       defaultEnv(),\n")
	b.WriteString("\t\tblocked:   defaultBlockedCommands(),\n")
	b.WriteString("\t\ttimeout:   60 * time.Second,\n")
	b.WriteString("\t\tmaxOutput: 30 * 1024, // 30KB\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	// defaultEnv
	b.WriteString("func defaultEnv() []string {\n")
	b.WriteString("\treturn []string{\n")
	b.WriteString("\t\t\"PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin\",\n")
	b.WriteString("\t\t\"HOME=\" + os.Getenv(\"HOME\"),\n")
	b.WriteString("\t\t\"USER=\" + os.Getenv(\"USER\"),\n")
	b.WriteString("\t\t\"TERM=dumb\",\n")
	b.WriteString("\t\t\"LANG=en_US.UTF-8\",\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	// defaultBlockedCommands — commands that should never be run by an agent
	b.WriteString("func defaultBlockedCommands() map[string]bool {\n")
	b.WriteString("\tblocked := map[string]bool{}\n")
	b.WriteString("\tfor _, cmd := range []string{\n")
	b.WriteString("\t\t\"sudo\", \"su\", \"doas\",\n")
	b.WriteString("\t\t\"rm\", \"rmdir\", \"mkfs\", \"fdisk\", \"dd\",\n")
	b.WriteString("\t\t\"shutdown\", \"reboot\", \"halt\", \"poweroff\",\n")
	b.WriteString("\t\t\"iptables\", \"ip6tables\", \"nft\", \"ufw\",\n")
	b.WriteString("\t\t\"systemctl\", \"service\", \"launchctl\",\n")
	b.WriteString("\t\t\"useradd\", \"userdel\", \"usermod\", \"groupadd\", \"passwd\",\n")
	b.WriteString("\t\t\"chmod\", \"chown\", \"chgrp\",\n")
	b.WriteString("\t\t\"mount\", \"umount\",\n")
	b.WriteString("\t\t\"kill\", \"killall\", \"pkill\",\n")
	b.WriteString("\t} {\n")
	b.WriteString("\t\tblocked[cmd] = true\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn blocked\n")
	b.WriteString("}\n\n")

	// Exec runs a command in the sandboxed shell
	b.WriteString("// Exec runs a command in the sandboxed shell and returns stdout/stderr.\n")
	b.WriteString("func (s *Shell) Exec(ctx context.Context, command string) (string, string, error) {\n")
	b.WriteString("\ts.mu.Lock()\n")
	b.WriteString("\tdefer s.mu.Unlock()\n\n")

	b.WriteString("\tctx, cancel := context.WithTimeout(ctx, s.timeout)\n")
	b.WriteString("\tdefer cancel()\n\n")

	// Parse the command
	b.WriteString("\tparser := syntax.NewParser()\n")
	b.WriteString("\tprog, err := parser.Parse(strings.NewReader(command), \"\")\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn \"\", \"\", fmt.Errorf(\"parse error: %w\", err)\n")
	b.WriteString("\t}\n\n")

	// Set up the interpreter with exec handler for blocking
	b.WriteString("\tvar stdout, stderr bytes.Buffer\n\n")

	b.WriteString("\t// Exec handler that blocks dangerous commands\n")
	b.WriteString("\tblocker := interp.ExecHandlers(func(next interp.ExecHandlerFunc) interp.ExecHandlerFunc {\n")
	b.WriteString("\t\treturn func(ctx context.Context, args []string) error {\n")
	b.WriteString("\t\t\tif len(args) > 0 && s.blocked[args[0]] {\n")
	b.WriteString("\t\t\t\treturn fmt.Errorf(\"command blocked: %s\", args[0])\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\treturn next(ctx, args)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t})\n\n")

	b.WriteString("\trunner, err := interp.New(\n")
	b.WriteString("\t\tinterp.Dir(s.workDir),\n")
	b.WriteString("\t\tinterp.Env(expand.ListEnviron(s.env...)),\n")
	b.WriteString("\t\tinterp.StdIO(nil, &stdout, &stderr),\n")
	b.WriteString("\t\tblocker,\n")
	b.WriteString("\t)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn \"\", \"\", fmt.Errorf(\"shell init: %w\", err)\n")
	b.WriteString("\t}\n\n")

	b.WriteString("\tif err := runner.Run(ctx, prog); err != nil {\n")
	b.WriteString("\t\treturn stdout.String(), stderr.String(), err\n")
	b.WriteString("\t}\n\n")

	// Update working directory from runner
	b.WriteString("\ts.workDir = runner.Dir\n\n")

	b.WriteString("\treturn stdout.String(), stderr.String(), nil\n")
	b.WriteString("}\n\n")

	// ShellInput for Fantasy tool
	b.WriteString("// ShellInput is the input schema for the shell tool.\n")
	b.WriteString("type ShellInput struct {\n")
	b.WriteString("\tCommand string `json:\"command\" description:\"The shell command to execute\"`\n")
	b.WriteString("}\n\n")

	// newShellTool creates the Fantasy agent tool
	b.WriteString("// newShellTool creates a Fantasy agent tool for sandboxed shell execution.\n")
	b.WriteString("func newShellTool(shell *Shell) fantasy.AgentTool {\n")
	b.WriteString("\treturn fantasy.NewAgentTool(\n")
	b.WriteString("\t\t\"shell\",\n")
	b.WriteString("\t\t\"Execute a shell command. Use this to run commands, read files, list directories, and interact with the system. Some dangerous commands are blocked for safety.\",\n")
	b.WriteString("\t\tfunc(ctx context.Context, input ShellInput, call fantasy.ToolCall) (fantasy.ToolResponse, error) {\n")
	b.WriteString("\t\t\tstdout, stderr, err := shell.Exec(ctx, input.Command)\n\n")
	b.WriteString("\t\t\tvar result strings.Builder\n")
	b.WriteString("\t\t\tif stdout != \"\" {\n")
	b.WriteString("\t\t\t\tresult.WriteString(stdout)\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tif stderr != \"\" {\n")
	b.WriteString("\t\t\t\tif result.Len() > 0 {\n")
	b.WriteString("\t\t\t\t\tresult.WriteString(\"\\n\")\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\t\tresult.WriteString(\"STDERR: \" + stderr)\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tif err != nil {\n")
	b.WriteString("\t\t\t\tif result.Len() > 0 {\n")
	b.WriteString("\t\t\t\t\tresult.WriteString(\"\\n\")\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\t\tresult.WriteString(fmt.Sprintf(\"ERROR: %v\", err))\n")
	b.WriteString("\t\t\t}\n\n")

	// Truncate if too large
	b.WriteString("\t\t\toutput := result.String()\n")
	b.WriteString("\t\t\tif len(output) > shell.maxOutput {\n")
	b.WriteString("\t\t\t\toutput = output[:shell.maxOutput] + \"\\n... (output truncated)\"\n")
	b.WriteString("\t\t\t}\n\n")

	b.WriteString("\t\t\tif err != nil {\n")
	b.WriteString("\t\t\t\treturn fantasy.ToolResponse{Type: \"text\", Content: output, IsError: true}, nil\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\treturn fantasy.ToolResponse{Type: \"text\", Content: output}, nil\n")
	b.WriteString("\t\t},\n")
	b.WriteString("\t)\n")
	b.WriteString("}\n")

	return b.String(), nil
}
