package generate

import (
	"strings"
	"testing"

	"github.com/charmbracelet/ayo/internal/schema"
	"github.com/charmbracelet/ayo/internal/testutil"
)

func TestGenerateTypes_InputOnly(t *testing.T) {
	inputSchema, _ := schema.ParseSchema([]byte(testutil.ValidInputSchema()))

	code, err := GenerateTypes(inputSchema, nil, "main")
	if err != nil {
		t.Fatalf("GenerateTypes() error = %v", err)
	}

	if !strings.Contains(code, "package main") {
		t.Error("Generated code should contain 'package main'")
	}

	if !strings.Contains(code, "type Input struct") {
		t.Error("Generated code should contain Input struct")
	}

	if strings.Contains(code, "type Output struct") {
		t.Error("Generated code should NOT contain Output struct")
	}

	if !strings.Contains(code, `json:"query"`) {
		t.Error("Generated code should contain JSON tag for query field")
	}
}

func TestGenerateTypes_OutputOnly(t *testing.T) {
	outputSchema, _ := schema.ParseSchema([]byte(testutil.ValidOutputSchema()))

	code, err := GenerateTypes(nil, outputSchema, "main")
	if err != nil {
		t.Fatalf("GenerateTypes() error = %v", err)
	}

	if !strings.Contains(code, "type Output struct") {
		t.Error("Generated code should contain Output struct")
	}

	if strings.Contains(code, "type Input struct") {
		t.Error("Generated code should NOT contain Input struct")
	}
}

func TestGenerateTypes_BothSchemas(t *testing.T) {
	inputSchema, _ := schema.ParseSchema([]byte(testutil.ValidInputSchema()))
	outputSchema, _ := schema.ParseSchema([]byte(testutil.ValidOutputSchema()))

	code, err := GenerateTypes(inputSchema, outputSchema, "cmd")
	if err != nil {
		t.Fatalf("GenerateTypes() error = %v", err)
	}

	if !strings.Contains(code, "type Input struct") {
		t.Error("Generated code should contain Input struct")
	}

	if !strings.Contains(code, "type Output struct") {
		t.Error("Generated code should contain Output struct")
	}

	if !strings.Contains(code, "package cmd") {
		t.Error("Generated code should use specified package name")
	}
}

func TestGenerateTypes_NilSchemas(t *testing.T) {
	code, err := GenerateTypes(nil, nil, "main")
	if err != nil {
		t.Fatalf("GenerateTypes() error = %v", err)
	}

	if !strings.Contains(code, "package main") {
		t.Error("Generated code should contain package declaration")
	}

	if strings.Contains(code, "type Input struct") {
		t.Error("Generated code should NOT contain Input struct")
	}

	if strings.Contains(code, "type Output struct") {
		t.Error("Generated code should NOT contain Output struct")
	}
}

func TestGenerateTypes_MultipleFields(t *testing.T) {
	schemaJSON := `{
		"type": "object",
		"properties": {
			"name": {"type": "string"},
			"age": {"type": "integer"},
			"score": {"type": "number"},
			"active": {"type": "boolean"},
			"tags": {"type": "array"},
			"metadata": {"type": "object"}
		}
	}`

	inputSchema, _ := schema.ParseSchema([]byte(schemaJSON))

	code, err := GenerateTypes(inputSchema, nil, "main")
	if err != nil {
		t.Fatalf("GenerateTypes() error = %v", err)
	}

	expectedFields := []struct {
		name     string
		goType   string
	}{
		{"Name", "string"},
		{"Age", "int"},
		{"Score", "float64"},
		{"Active", "bool"},
		{"Tags", "[]any"},
		{"Metadata", "map[string]any"},
	}

	for _, ef := range expectedFields {
		if !strings.Contains(code, ef.name+" "+ef.goType) {
			t.Errorf("Generated code missing field %s %s", ef.name, ef.goType)
		}
	}
}

func TestJsonTypeToGo(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"string", "string"},
		{"integer", "int"},
		{"number", "float64"},
		{"boolean", "bool"},
		{"array", "[]any"},
		{"object", "map[string]any"},
		{"unknown", "any"},
		{"", "any"},
	}

	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			got := jsonTypeToGo(tt.input)
			if got != tt.expected {
				t.Errorf("jsonTypeToGo(%q) = %q, want %q", tt.input, got, tt.expected)
			}
		})
	}
}

func TestToPascalCase(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"name", "Name"},
		{"query", "Query"},
		{"my_field", "My_field"},
		{"a", "A"},
		{"", ""},
		{"alreadyCapital", "AlreadyCapital"},
		{"1number", "1number"},
	}

	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			got := toPascalCase(tt.input)
			if got != tt.expected {
				t.Errorf("toPascalCase(%q) = %q, want %q", tt.input, got, tt.expected)
			}
		})
	}
}

func TestGenerateTypes_GeneratedHeader(t *testing.T) {
	inputSchema, _ := schema.ParseSchema([]byte(testutil.ValidInputSchema()))

	code, err := GenerateTypes(inputSchema, nil, "main")
	if err != nil {
		t.Fatalf("GenerateTypes() error = %v", err)
	}

	if !strings.Contains(code, "// Code generated by ayo. DO NOT EDIT.") {
		t.Error("Generated code should contain generation header")
	}
}
