package generate

import (
	"fmt"
	"strings"

	"github.com/charmbracelet/ayo/internal/schema"
)

func GenerateTypes(inputSchema, outputSchema *schema.ParsedSchema, pkgName string) (string, error) {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("// Code generated by ayo. DO NOT EDIT.\n\npackage %s\n\n", pkgName))

	if inputSchema != nil {
		b.WriteString("// Input represents the structured input for the agent.\n")
		b.WriteString("type Input struct {\n")
		for name, prop := range inputSchema.Properties {
			goType := jsonTypeToGo(prop.Type)
			fieldName := toPascalCase(name)
			b.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", fieldName, goType, name))
		}
		b.WriteString("}\n\n")
	}

	if outputSchema != nil {
		b.WriteString("// Output represents the structured output from the agent.\n")
		b.WriteString("type Output struct {\n")
		for name, prop := range outputSchema.Properties {
			goType := jsonTypeToGo(prop.Type)
			fieldName := toPascalCase(name)
			b.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", fieldName, goType, name))
		}
		b.WriteString("}\n\n")
	}

	return b.String(), nil
}

func jsonTypeToGo(jsonType string) string {
	switch jsonType {
	case "string":
		return "string"
	case "integer":
		return "int"
	case "number":
		return "float64"
	case "boolean":
		return "bool"
	case "array":
		return "[]any"
	case "object":
		return "map[string]any"
	default:
		return "any"
	}
}

func toPascalCase(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
