// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ayo_agents.sql

package db

import (
	"context"
	"database/sql"
)

const archiveAyoAgent = `-- name: ArchiveAyoAgent :exec
UPDATE ayo_created_agents
SET is_archived = 1,
    updated_at = ?
WHERE agent_id = ?
`

type ArchiveAyoAgentParams struct {
	UpdatedAt int64  `json:"updated_at"`
	AgentID   string `json:"agent_id"`
}

func (q *Queries) ArchiveAyoAgent(ctx context.Context, arg ArchiveAyoAgentParams) error {
	_, err := q.exec(ctx, q.archiveAyoAgentStmt, archiveAyoAgent, arg.UpdatedAt, arg.AgentID)
	return err
}

const createAgentRefinement = `-- name: CreateAgentRefinement :exec
INSERT INTO agent_refinements (
    id,
    agent_id,
    previous_prompt,
    new_prompt,
    reason,
    created_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateAgentRefinementParams struct {
	ID             string `json:"id"`
	AgentID        string `json:"agent_id"`
	PreviousPrompt string `json:"previous_prompt"`
	NewPrompt      string `json:"new_prompt"`
	Reason         string `json:"reason"`
	CreatedAt      int64  `json:"created_at"`
}

func (q *Queries) CreateAgentRefinement(ctx context.Context, arg CreateAgentRefinementParams) error {
	_, err := q.exec(ctx, q.createAgentRefinementStmt, createAgentRefinement,
		arg.ID,
		arg.AgentID,
		arg.PreviousPrompt,
		arg.NewPrompt,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}

const createAyoAgent = `-- name: CreateAyoAgent :exec
INSERT INTO ayo_created_agents (
    agent_id,
    agent_handle,
    created_by,
    creation_reason,
    original_prompt,
    current_prompt_hash,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAyoAgentParams struct {
	AgentID           string         `json:"agent_id"`
	AgentHandle       string         `json:"agent_handle"`
	CreatedBy         string         `json:"created_by"`
	CreationReason    sql.NullString `json:"creation_reason"`
	OriginalPrompt    string         `json:"original_prompt"`
	CurrentPromptHash sql.NullString `json:"current_prompt_hash"`
	CreatedAt         int64          `json:"created_at"`
	UpdatedAt         int64          `json:"updated_at"`
}

func (q *Queries) CreateAyoAgent(ctx context.Context, arg CreateAyoAgentParams) error {
	_, err := q.exec(ctx, q.createAyoAgentStmt, createAyoAgent,
		arg.AgentID,
		arg.AgentHandle,
		arg.CreatedBy,
		arg.CreationReason,
		arg.OriginalPrompt,
		arg.CurrentPromptHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteAyoAgent = `-- name: DeleteAyoAgent :exec
DELETE FROM ayo_created_agents WHERE agent_id = ?
`

func (q *Queries) DeleteAyoAgent(ctx context.Context, agentID string) error {
	_, err := q.exec(ctx, q.deleteAyoAgentStmt, deleteAyoAgent, agentID)
	return err
}

const getAyoAgent = `-- name: GetAyoAgent :one
SELECT agent_id, agent_handle, created_by, creation_reason, original_prompt, invocation_count, success_count, failure_count, last_used_at, refinement_count, current_prompt_hash, confidence, is_archived, promoted_to, created_at, updated_at FROM ayo_created_agents WHERE agent_id = ?
`

func (q *Queries) GetAyoAgent(ctx context.Context, agentID string) (AyoCreatedAgent, error) {
	row := q.queryRow(ctx, q.getAyoAgentStmt, getAyoAgent, agentID)
	var i AyoCreatedAgent
	err := row.Scan(
		&i.AgentID,
		&i.AgentHandle,
		&i.CreatedBy,
		&i.CreationReason,
		&i.OriginalPrompt,
		&i.InvocationCount,
		&i.SuccessCount,
		&i.FailureCount,
		&i.LastUsedAt,
		&i.RefinementCount,
		&i.CurrentPromptHash,
		&i.Confidence,
		&i.IsArchived,
		&i.PromotedTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAyoAgentByHandle = `-- name: GetAyoAgentByHandle :one
SELECT agent_id, agent_handle, created_by, creation_reason, original_prompt, invocation_count, success_count, failure_count, last_used_at, refinement_count, current_prompt_hash, confidence, is_archived, promoted_to, created_at, updated_at FROM ayo_created_agents WHERE agent_handle = ?
`

func (q *Queries) GetAyoAgentByHandle(ctx context.Context, agentHandle string) (AyoCreatedAgent, error) {
	row := q.queryRow(ctx, q.getAyoAgentByHandleStmt, getAyoAgentByHandle, agentHandle)
	var i AyoCreatedAgent
	err := row.Scan(
		&i.AgentID,
		&i.AgentHandle,
		&i.CreatedBy,
		&i.CreationReason,
		&i.OriginalPrompt,
		&i.InvocationCount,
		&i.SuccessCount,
		&i.FailureCount,
		&i.LastUsedAt,
		&i.RefinementCount,
		&i.CurrentPromptHash,
		&i.Confidence,
		&i.IsArchived,
		&i.PromotedTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestRefinement = `-- name: GetLatestRefinement :one
SELECT id, agent_id, previous_prompt, new_prompt, reason, created_at FROM agent_refinements
WHERE agent_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestRefinement(ctx context.Context, agentID string) (AgentRefinement, error) {
	row := q.queryRow(ctx, q.getLatestRefinementStmt, getLatestRefinement, agentID)
	var i AgentRefinement
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.PreviousPrompt,
		&i.NewPrompt,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentRefinements = `-- name: ListAgentRefinements :many
SELECT id, agent_id, previous_prompt, new_prompt, reason, created_at FROM agent_refinements
WHERE agent_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListAgentRefinements(ctx context.Context, agentID string) ([]AgentRefinement, error) {
	rows, err := q.query(ctx, q.listAgentRefinementsStmt, listAgentRefinements, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRefinement{}
	for rows.Next() {
		var i AgentRefinement
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.PreviousPrompt,
			&i.NewPrompt,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchivedAyoAgents = `-- name: ListArchivedAyoAgents :many
SELECT agent_id, agent_handle, created_by, creation_reason, original_prompt, invocation_count, success_count, failure_count, last_used_at, refinement_count, current_prompt_hash, confidence, is_archived, promoted_to, created_at, updated_at FROM ayo_created_agents
WHERE is_archived = 1
ORDER BY updated_at DESC
`

func (q *Queries) ListArchivedAyoAgents(ctx context.Context) ([]AyoCreatedAgent, error) {
	rows, err := q.query(ctx, q.listArchivedAyoAgentsStmt, listArchivedAyoAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AyoCreatedAgent{}
	for rows.Next() {
		var i AyoCreatedAgent
		if err := rows.Scan(
			&i.AgentID,
			&i.AgentHandle,
			&i.CreatedBy,
			&i.CreationReason,
			&i.OriginalPrompt,
			&i.InvocationCount,
			&i.SuccessCount,
			&i.FailureCount,
			&i.LastUsedAt,
			&i.RefinementCount,
			&i.CurrentPromptHash,
			&i.Confidence,
			&i.IsArchived,
			&i.PromotedTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAyoAgents = `-- name: ListAyoAgents :many
SELECT agent_id, agent_handle, created_by, creation_reason, original_prompt, invocation_count, success_count, failure_count, last_used_at, refinement_count, current_prompt_hash, confidence, is_archived, promoted_to, created_at, updated_at FROM ayo_created_agents
WHERE is_archived = 0
ORDER BY last_used_at DESC NULLS LAST, created_at DESC
`

func (q *Queries) ListAyoAgents(ctx context.Context) ([]AyoCreatedAgent, error) {
	rows, err := q.query(ctx, q.listAyoAgentsStmt, listAyoAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AyoCreatedAgent{}
	for rows.Next() {
		var i AyoCreatedAgent
		if err := rows.Scan(
			&i.AgentID,
			&i.AgentHandle,
			&i.CreatedBy,
			&i.CreationReason,
			&i.OriginalPrompt,
			&i.InvocationCount,
			&i.SuccessCount,
			&i.FailureCount,
			&i.LastUsedAt,
			&i.RefinementCount,
			&i.CurrentPromptHash,
			&i.Confidence,
			&i.IsArchived,
			&i.PromotedTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteAyoAgent = `-- name: PromoteAyoAgent :exec
UPDATE ayo_created_agents
SET promoted_to = ?,
    updated_at = ?
WHERE agent_id = ?
`

type PromoteAyoAgentParams struct {
	PromotedTo sql.NullString `json:"promoted_to"`
	UpdatedAt  int64          `json:"updated_at"`
	AgentID    string         `json:"agent_id"`
}

func (q *Queries) PromoteAyoAgent(ctx context.Context, arg PromoteAyoAgentParams) error {
	_, err := q.exec(ctx, q.promoteAyoAgentStmt, promoteAyoAgent, arg.PromotedTo, arg.UpdatedAt, arg.AgentID)
	return err
}

const unarchiveAyoAgent = `-- name: UnarchiveAyoAgent :exec
UPDATE ayo_created_agents
SET is_archived = 0,
    updated_at = ?
WHERE agent_id = ?
`

type UnarchiveAyoAgentParams struct {
	UpdatedAt int64  `json:"updated_at"`
	AgentID   string `json:"agent_id"`
}

func (q *Queries) UnarchiveAyoAgent(ctx context.Context, arg UnarchiveAyoAgentParams) error {
	_, err := q.exec(ctx, q.unarchiveAyoAgentStmt, unarchiveAyoAgent, arg.UpdatedAt, arg.AgentID)
	return err
}

const updateAyoAgentFailure = `-- name: UpdateAyoAgentFailure :exec
UPDATE ayo_created_agents
SET failure_count = failure_count + 1,
    confidence = MAX(0.0, confidence - 0.1),
    updated_at = ?
WHERE agent_id = ?
`

type UpdateAyoAgentFailureParams struct {
	UpdatedAt int64  `json:"updated_at"`
	AgentID   string `json:"agent_id"`
}

func (q *Queries) UpdateAyoAgentFailure(ctx context.Context, arg UpdateAyoAgentFailureParams) error {
	_, err := q.exec(ctx, q.updateAyoAgentFailureStmt, updateAyoAgentFailure, arg.UpdatedAt, arg.AgentID)
	return err
}

const updateAyoAgentInvocation = `-- name: UpdateAyoAgentInvocation :exec
UPDATE ayo_created_agents
SET invocation_count = invocation_count + 1,
    last_used_at = ?,
    updated_at = ?
WHERE agent_id = ?
`

type UpdateAyoAgentInvocationParams struct {
	LastUsedAt sql.NullInt64 `json:"last_used_at"`
	UpdatedAt  int64         `json:"updated_at"`
	AgentID    string        `json:"agent_id"`
}

func (q *Queries) UpdateAyoAgentInvocation(ctx context.Context, arg UpdateAyoAgentInvocationParams) error {
	_, err := q.exec(ctx, q.updateAyoAgentInvocationStmt, updateAyoAgentInvocation, arg.LastUsedAt, arg.UpdatedAt, arg.AgentID)
	return err
}

const updateAyoAgentPrompt = `-- name: UpdateAyoAgentPrompt :exec
UPDATE ayo_created_agents
SET current_prompt_hash = ?,
    refinement_count = refinement_count + 1,
    updated_at = ?
WHERE agent_id = ?
`

type UpdateAyoAgentPromptParams struct {
	CurrentPromptHash sql.NullString `json:"current_prompt_hash"`
	UpdatedAt         int64          `json:"updated_at"`
	AgentID           string         `json:"agent_id"`
}

func (q *Queries) UpdateAyoAgentPrompt(ctx context.Context, arg UpdateAyoAgentPromptParams) error {
	_, err := q.exec(ctx, q.updateAyoAgentPromptStmt, updateAyoAgentPrompt, arg.CurrentPromptHash, arg.UpdatedAt, arg.AgentID)
	return err
}

const updateAyoAgentSuccess = `-- name: UpdateAyoAgentSuccess :exec
UPDATE ayo_created_agents
SET success_count = success_count + 1,
    confidence = MIN(1.0, confidence + 0.05),
    updated_at = ?
WHERE agent_id = ?
`

type UpdateAyoAgentSuccessParams struct {
	UpdatedAt int64  `json:"updated_at"`
	AgentID   string `json:"agent_id"`
}

func (q *Queries) UpdateAyoAgentSuccess(ctx context.Context, arg UpdateAyoAgentSuccessParams) error {
	_, err := q.exec(ctx, q.updateAyoAgentSuccessStmt, updateAyoAgentSuccess, arg.UpdatedAt, arg.AgentID)
	return err
}
