// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: capabilities.sql

package db

import (
	"context"
)

const createCapability = `-- name: CreateCapability :exec
INSERT INTO agent_capabilities (
    id,
    agent_id,
    name,
    description,
    confidence,
    source,
    embedding,
    input_hash,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCapabilityParams struct {
	ID          string  `json:"id"`
	AgentID     string  `json:"agent_id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Confidence  float64 `json:"confidence"`
	Source      string  `json:"source"`
	Embedding   []byte  `json:"embedding"`
	InputHash   string  `json:"input_hash"`
	CreatedAt   int64   `json:"created_at"`
	UpdatedAt   int64   `json:"updated_at"`
}

func (q *Queries) CreateCapability(ctx context.Context, arg CreateCapabilityParams) error {
	_, err := q.exec(ctx, q.createCapabilityStmt, createCapability,
		arg.ID,
		arg.AgentID,
		arg.Name,
		arg.Description,
		arg.Confidence,
		arg.Source,
		arg.Embedding,
		arg.InputHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteCapabilitiesByAgent = `-- name: DeleteCapabilitiesByAgent :exec
DELETE FROM agent_capabilities WHERE agent_id = ?
`

func (q *Queries) DeleteCapabilitiesByAgent(ctx context.Context, agentID string) error {
	_, err := q.exec(ctx, q.deleteCapabilitiesByAgentStmt, deleteCapabilitiesByAgent, agentID)
	return err
}

const getCapabilitiesByAgent = `-- name: GetCapabilitiesByAgent :many
SELECT id, agent_id, name, description, confidence, source, embedding, input_hash, created_at, updated_at FROM agent_capabilities
WHERE agent_id = ?
ORDER BY confidence DESC
`

func (q *Queries) GetCapabilitiesByAgent(ctx context.Context, agentID string) ([]AgentCapability, error) {
	rows, err := q.query(ctx, q.getCapabilitiesByAgentStmt, getCapabilitiesByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentCapability{}
	for rows.Next() {
		var i AgentCapability
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Name,
			&i.Description,
			&i.Confidence,
			&i.Source,
			&i.Embedding,
			&i.InputHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCapabilitiesByHash = `-- name: GetCapabilitiesByHash :many
SELECT id, agent_id, name, description, confidence, source, embedding, input_hash, created_at, updated_at FROM agent_capabilities
WHERE input_hash = ?
`

func (q *Queries) GetCapabilitiesByHash(ctx context.Context, inputHash string) ([]AgentCapability, error) {
	rows, err := q.query(ctx, q.getCapabilitiesByHashStmt, getCapabilitiesByHash, inputHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentCapability{}
	for rows.Next() {
		var i AgentCapability
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Name,
			&i.Description,
			&i.Confidence,
			&i.Source,
			&i.Embedding,
			&i.InputHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCapabilityByName = `-- name: GetCapabilityByName :one
SELECT id, agent_id, name, description, confidence, source, embedding, input_hash, created_at, updated_at FROM agent_capabilities
WHERE agent_id = ? AND name = ?
`

type GetCapabilityByNameParams struct {
	AgentID string `json:"agent_id"`
	Name    string `json:"name"`
}

func (q *Queries) GetCapabilityByName(ctx context.Context, arg GetCapabilityByNameParams) (AgentCapability, error) {
	row := q.queryRow(ctx, q.getCapabilityByNameStmt, getCapabilityByName, arg.AgentID, arg.Name)
	var i AgentCapability
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Name,
		&i.Description,
		&i.Confidence,
		&i.Source,
		&i.Embedding,
		&i.InputHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllCapabilities = `-- name: ListAllCapabilities :many
SELECT id, agent_id, name, description, confidence, source, embedding, input_hash, created_at, updated_at FROM agent_capabilities
ORDER BY confidence DESC
`

func (q *Queries) ListAllCapabilities(ctx context.Context) ([]AgentCapability, error) {
	rows, err := q.query(ctx, q.listAllCapabilitiesStmt, listAllCapabilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentCapability{}
	for rows.Next() {
		var i AgentCapability
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Name,
			&i.Description,
			&i.Confidence,
			&i.Source,
			&i.Embedding,
			&i.InputHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCapabilitiesByName = `-- name: SearchCapabilitiesByName :many
SELECT id, agent_id, name, description, confidence, source, embedding, input_hash, created_at, updated_at FROM agent_capabilities
WHERE name LIKE ? OR description LIKE ?
ORDER BY confidence DESC
LIMIT ?
`

type SearchCapabilitiesByNameParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Limit       int64  `json:"limit"`
}

func (q *Queries) SearchCapabilitiesByName(ctx context.Context, arg SearchCapabilitiesByNameParams) ([]AgentCapability, error) {
	rows, err := q.query(ctx, q.searchCapabilitiesByNameStmt, searchCapabilitiesByName, arg.Name, arg.Description, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentCapability{}
	for rows.Next() {
		var i AgentCapability
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Name,
			&i.Description,
			&i.Confidence,
			&i.Source,
			&i.Embedding,
			&i.InputHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCapabilityEmbedding = `-- name: UpdateCapabilityEmbedding :exec
UPDATE agent_capabilities
SET embedding = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateCapabilityEmbeddingParams struct {
	Embedding []byte `json:"embedding"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateCapabilityEmbedding(ctx context.Context, arg UpdateCapabilityEmbeddingParams) error {
	_, err := q.exec(ctx, q.updateCapabilityEmbeddingStmt, updateCapabilityEmbedding, arg.Embedding, arg.UpdatedAt, arg.ID)
	return err
}
