// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.clearAllMemoriesStmt, err = db.PrepareContext(ctx, clearAllMemories); err != nil {
		return nil, fmt.Errorf("error preparing query ClearAllMemories: %w", err)
	}
	if q.clearMemoriesByAgentStmt, err = db.PrepareContext(ctx, clearMemoriesByAgent); err != nil {
		return nil, fmt.Errorf("error preparing query ClearMemoriesByAgent: %w", err)
	}
	if q.completeFlowRunStmt, err = db.PrepareContext(ctx, completeFlowRun); err != nil {
		return nil, fmt.Errorf("error preparing query CompleteFlowRun: %w", err)
	}
	if q.countFlowRunsStmt, err = db.PrepareContext(ctx, countFlowRuns); err != nil {
		return nil, fmt.Errorf("error preparing query CountFlowRuns: %w", err)
	}
	if q.countFlowRunsByNameStmt, err = db.PrepareContext(ctx, countFlowRunsByName); err != nil {
		return nil, fmt.Errorf("error preparing query CountFlowRunsByName: %w", err)
	}
	if q.countFlowRunsByStatusStmt, err = db.PrepareContext(ctx, countFlowRunsByStatus); err != nil {
		return nil, fmt.Errorf("error preparing query CountFlowRunsByStatus: %w", err)
	}
	if q.countMemoriesStmt, err = db.PrepareContext(ctx, countMemories); err != nil {
		return nil, fmt.Errorf("error preparing query CountMemories: %w", err)
	}
	if q.countMemoriesByAgentStmt, err = db.PrepareContext(ctx, countMemoriesByAgent); err != nil {
		return nil, fmt.Errorf("error preparing query CountMemoriesByAgent: %w", err)
	}
	if q.countMessagesBySessionStmt, err = db.PrepareContext(ctx, countMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query CountMessagesBySession: %w", err)
	}
	if q.countSessionsStmt, err = db.PrepareContext(ctx, countSessions); err != nil {
		return nil, fmt.Errorf("error preparing query CountSessions: %w", err)
	}
	if q.countSessionsByAgentStmt, err = db.PrepareContext(ctx, countSessionsByAgent); err != nil {
		return nil, fmt.Errorf("error preparing query CountSessionsByAgent: %w", err)
	}
	if q.countSessionsBySourceStmt, err = db.PrepareContext(ctx, countSessionsBySource); err != nil {
		return nil, fmt.Errorf("error preparing query CountSessionsBySource: %w", err)
	}
	if q.createEdgeStmt, err = db.PrepareContext(ctx, createEdge); err != nil {
		return nil, fmt.Errorf("error preparing query CreateEdge: %w", err)
	}
	if q.createFlowRunStmt, err = db.PrepareContext(ctx, createFlowRun); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFlowRun: %w", err)
	}
	if q.createMemoryStmt, err = db.PrepareContext(ctx, createMemory); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMemory: %w", err)
	}
	if q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessage: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.deleteEdgeStmt, err = db.PrepareContext(ctx, deleteEdge); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteEdge: %w", err)
	}
	if q.deleteEdgesBySessionStmt, err = db.PrepareContext(ctx, deleteEdgesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteEdgesBySession: %w", err)
	}
	if q.deleteFlowRunStmt, err = db.PrepareContext(ctx, deleteFlowRun); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFlowRun: %w", err)
	}
	if q.deleteMemoryStmt, err = db.PrepareContext(ctx, deleteMemory); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMemory: %w", err)
	}
	if q.deleteMessageStmt, err = db.PrepareContext(ctx, deleteMessage); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMessage: %w", err)
	}
	if q.deleteMessagesBySessionStmt, err = db.PrepareContext(ctx, deleteMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMessagesBySession: %w", err)
	}
	if q.deleteSessionStmt, err = db.PrepareContext(ctx, deleteSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSession: %w", err)
	}
	if q.forgetMemoryStmt, err = db.PrepareContext(ctx, forgetMemory); err != nil {
		return nil, fmt.Errorf("error preparing query ForgetMemory: %w", err)
	}
	if q.getAllActiveMemoriesWithEmbeddingsStmt, err = db.PrepareContext(ctx, getAllActiveMemoriesWithEmbeddings); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllActiveMemoriesWithEmbeddings: %w", err)
	}
	if q.getChildEdgesStmt, err = db.PrepareContext(ctx, getChildEdges); err != nil {
		return nil, fmt.Errorf("error preparing query GetChildEdges: %w", err)
	}
	if q.getFlowRunStmt, err = db.PrepareContext(ctx, getFlowRun); err != nil {
		return nil, fmt.Errorf("error preparing query GetFlowRun: %w", err)
	}
	if q.getFlowRunByPrefixStmt, err = db.PrepareContext(ctx, getFlowRunByPrefix); err != nil {
		return nil, fmt.Errorf("error preparing query GetFlowRunByPrefix: %w", err)
	}
	if q.getLastFlowRunStmt, err = db.PrepareContext(ctx, getLastFlowRun); err != nil {
		return nil, fmt.Errorf("error preparing query GetLastFlowRun: %w", err)
	}
	if q.getMemoriesForSearchStmt, err = db.PrepareContext(ctx, getMemoriesForSearch); err != nil {
		return nil, fmt.Errorf("error preparing query GetMemoriesForSearch: %w", err)
	}
	if q.getMemoryStmt, err = db.PrepareContext(ctx, getMemory); err != nil {
		return nil, fmt.Errorf("error preparing query GetMemory: %w", err)
	}
	if q.getMemoryHistoryStmt, err = db.PrepareContext(ctx, getMemoryHistory); err != nil {
		return nil, fmt.Errorf("error preparing query GetMemoryHistory: %w", err)
	}
	if q.getMessageStmt, err = db.PrepareContext(ctx, getMessage); err != nil {
		return nil, fmt.Errorf("error preparing query GetMessage: %w", err)
	}
	if q.getParentEdgesStmt, err = db.PrepareContext(ctx, getParentEdges); err != nil {
		return nil, fmt.Errorf("error preparing query GetParentEdges: %w", err)
	}
	if q.getSessionStmt, err = db.PrepareContext(ctx, getSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetSession: %w", err)
	}
	if q.getSessionByPrefixStmt, err = db.PrepareContext(ctx, getSessionByPrefix); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionByPrefix: %w", err)
	}
	if q.listFlowRunsStmt, err = db.PrepareContext(ctx, listFlowRuns); err != nil {
		return nil, fmt.Errorf("error preparing query ListFlowRuns: %w", err)
	}
	if q.listFlowRunsByNameStmt, err = db.PrepareContext(ctx, listFlowRunsByName); err != nil {
		return nil, fmt.Errorf("error preparing query ListFlowRunsByName: %w", err)
	}
	if q.listFlowRunsBySessionStmt, err = db.PrepareContext(ctx, listFlowRunsBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListFlowRunsBySession: %w", err)
	}
	if q.listFlowRunsByStatusStmt, err = db.PrepareContext(ctx, listFlowRunsByStatus); err != nil {
		return nil, fmt.Errorf("error preparing query ListFlowRunsByStatus: %w", err)
	}
	if q.listMemoriesStmt, err = db.PrepareContext(ctx, listMemories); err != nil {
		return nil, fmt.Errorf("error preparing query ListMemories: %w", err)
	}
	if q.listMemoriesByAgentStmt, err = db.PrepareContext(ctx, listMemoriesByAgent); err != nil {
		return nil, fmt.Errorf("error preparing query ListMemoriesByAgent: %w", err)
	}
	if q.listMemoriesByAgentAndPathStmt, err = db.PrepareContext(ctx, listMemoriesByAgentAndPath); err != nil {
		return nil, fmt.Errorf("error preparing query ListMemoriesByAgentAndPath: %w", err)
	}
	if q.listMemoriesByCategoryStmt, err = db.PrepareContext(ctx, listMemoriesByCategory); err != nil {
		return nil, fmt.Errorf("error preparing query ListMemoriesByCategory: %w", err)
	}
	if q.listMemoriesByPathStmt, err = db.PrepareContext(ctx, listMemoriesByPath); err != nil {
		return nil, fmt.Errorf("error preparing query ListMemoriesByPath: %w", err)
	}
	if q.listMessagesBySessionStmt, err = db.PrepareContext(ctx, listMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesBySession: %w", err)
	}
	if q.listSessionsStmt, err = db.PrepareContext(ctx, listSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessions: %w", err)
	}
	if q.listSessionsByAgentStmt, err = db.PrepareContext(ctx, listSessionsByAgent); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionsByAgent: %w", err)
	}
	if q.listSessionsBySourceStmt, err = db.PrepareContext(ctx, listSessionsBySource); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionsBySource: %w", err)
	}
	if q.pruneFlowRunsByAgeStmt, err = db.PrepareContext(ctx, pruneFlowRunsByAge); err != nil {
		return nil, fmt.Errorf("error preparing query PruneFlowRunsByAge: %w", err)
	}
	if q.pruneFlowRunsByCountStmt, err = db.PrepareContext(ctx, pruneFlowRunsByCount); err != nil {
		return nil, fmt.Errorf("error preparing query PruneFlowRunsByCount: %w", err)
	}
	if q.searchSessionsByTitleStmt, err = db.PrepareContext(ctx, searchSessionsByTitle); err != nil {
		return nil, fmt.Errorf("error preparing query SearchSessionsByTitle: %w", err)
	}
	if q.supersedeMemoryStmt, err = db.PrepareContext(ctx, supersedeMemory); err != nil {
		return nil, fmt.Errorf("error preparing query SupersedeMemory: %w", err)
	}
	if q.updateMemoryStmt, err = db.PrepareContext(ctx, updateMemory); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMemory: %w", err)
	}
	if q.updateMemoryAccessStmt, err = db.PrepareContext(ctx, updateMemoryAccess); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMemoryAccess: %w", err)
	}
	if q.updateMessageStmt, err = db.PrepareContext(ctx, updateMessage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMessage: %w", err)
	}
	if q.updateSessionStmt, err = db.PrepareContext(ctx, updateSession); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSession: %w", err)
	}
	if q.updateSessionTitleStmt, err = db.PrepareContext(ctx, updateSessionTitle); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSessionTitle: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.clearAllMemoriesStmt != nil {
		if cerr := q.clearAllMemoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearAllMemoriesStmt: %w", cerr)
		}
	}
	if q.clearMemoriesByAgentStmt != nil {
		if cerr := q.clearMemoriesByAgentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearMemoriesByAgentStmt: %w", cerr)
		}
	}
	if q.completeFlowRunStmt != nil {
		if cerr := q.completeFlowRunStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing completeFlowRunStmt: %w", cerr)
		}
	}
	if q.countFlowRunsStmt != nil {
		if cerr := q.countFlowRunsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countFlowRunsStmt: %w", cerr)
		}
	}
	if q.countFlowRunsByNameStmt != nil {
		if cerr := q.countFlowRunsByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countFlowRunsByNameStmt: %w", cerr)
		}
	}
	if q.countFlowRunsByStatusStmt != nil {
		if cerr := q.countFlowRunsByStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countFlowRunsByStatusStmt: %w", cerr)
		}
	}
	if q.countMemoriesStmt != nil {
		if cerr := q.countMemoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countMemoriesStmt: %w", cerr)
		}
	}
	if q.countMemoriesByAgentStmt != nil {
		if cerr := q.countMemoriesByAgentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countMemoriesByAgentStmt: %w", cerr)
		}
	}
	if q.countMessagesBySessionStmt != nil {
		if cerr := q.countMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.countSessionsStmt != nil {
		if cerr := q.countSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countSessionsStmt: %w", cerr)
		}
	}
	if q.countSessionsByAgentStmt != nil {
		if cerr := q.countSessionsByAgentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countSessionsByAgentStmt: %w", cerr)
		}
	}
	if q.countSessionsBySourceStmt != nil {
		if cerr := q.countSessionsBySourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countSessionsBySourceStmt: %w", cerr)
		}
	}
	if q.createEdgeStmt != nil {
		if cerr := q.createEdgeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createEdgeStmt: %w", cerr)
		}
	}
	if q.createFlowRunStmt != nil {
		if cerr := q.createFlowRunStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFlowRunStmt: %w", cerr)
		}
	}
	if q.createMemoryStmt != nil {
		if cerr := q.createMemoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMemoryStmt: %w", cerr)
		}
	}
	if q.createMessageStmt != nil {
		if cerr := q.createMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.deleteEdgeStmt != nil {
		if cerr := q.deleteEdgeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteEdgeStmt: %w", cerr)
		}
	}
	if q.deleteEdgesBySessionStmt != nil {
		if cerr := q.deleteEdgesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteEdgesBySessionStmt: %w", cerr)
		}
	}
	if q.deleteFlowRunStmt != nil {
		if cerr := q.deleteFlowRunStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFlowRunStmt: %w", cerr)
		}
	}
	if q.deleteMemoryStmt != nil {
		if cerr := q.deleteMemoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMemoryStmt: %w", cerr)
		}
	}
	if q.deleteMessageStmt != nil {
		if cerr := q.deleteMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMessageStmt: %w", cerr)
		}
	}
	if q.deleteMessagesBySessionStmt != nil {
		if cerr := q.deleteMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.deleteSessionStmt != nil {
		if cerr := q.deleteSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionStmt: %w", cerr)
		}
	}
	if q.forgetMemoryStmt != nil {
		if cerr := q.forgetMemoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing forgetMemoryStmt: %w", cerr)
		}
	}
	if q.getAllActiveMemoriesWithEmbeddingsStmt != nil {
		if cerr := q.getAllActiveMemoriesWithEmbeddingsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllActiveMemoriesWithEmbeddingsStmt: %w", cerr)
		}
	}
	if q.getChildEdgesStmt != nil {
		if cerr := q.getChildEdgesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChildEdgesStmt: %w", cerr)
		}
	}
	if q.getFlowRunStmt != nil {
		if cerr := q.getFlowRunStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFlowRunStmt: %w", cerr)
		}
	}
	if q.getFlowRunByPrefixStmt != nil {
		if cerr := q.getFlowRunByPrefixStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFlowRunByPrefixStmt: %w", cerr)
		}
	}
	if q.getLastFlowRunStmt != nil {
		if cerr := q.getLastFlowRunStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLastFlowRunStmt: %w", cerr)
		}
	}
	if q.getMemoriesForSearchStmt != nil {
		if cerr := q.getMemoriesForSearchStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMemoriesForSearchStmt: %w", cerr)
		}
	}
	if q.getMemoryStmt != nil {
		if cerr := q.getMemoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMemoryStmt: %w", cerr)
		}
	}
	if q.getMemoryHistoryStmt != nil {
		if cerr := q.getMemoryHistoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMemoryHistoryStmt: %w", cerr)
		}
	}
	if q.getMessageStmt != nil {
		if cerr := q.getMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMessageStmt: %w", cerr)
		}
	}
	if q.getParentEdgesStmt != nil {
		if cerr := q.getParentEdgesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getParentEdgesStmt: %w", cerr)
		}
	}
	if q.getSessionStmt != nil {
		if cerr := q.getSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionStmt: %w", cerr)
		}
	}
	if q.getSessionByPrefixStmt != nil {
		if cerr := q.getSessionByPrefixStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByPrefixStmt: %w", cerr)
		}
	}
	if q.listFlowRunsStmt != nil {
		if cerr := q.listFlowRunsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFlowRunsStmt: %w", cerr)
		}
	}
	if q.listFlowRunsByNameStmt != nil {
		if cerr := q.listFlowRunsByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFlowRunsByNameStmt: %w", cerr)
		}
	}
	if q.listFlowRunsBySessionStmt != nil {
		if cerr := q.listFlowRunsBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFlowRunsBySessionStmt: %w", cerr)
		}
	}
	if q.listFlowRunsByStatusStmt != nil {
		if cerr := q.listFlowRunsByStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFlowRunsByStatusStmt: %w", cerr)
		}
	}
	if q.listMemoriesStmt != nil {
		if cerr := q.listMemoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMemoriesStmt: %w", cerr)
		}
	}
	if q.listMemoriesByAgentStmt != nil {
		if cerr := q.listMemoriesByAgentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMemoriesByAgentStmt: %w", cerr)
		}
	}
	if q.listMemoriesByAgentAndPathStmt != nil {
		if cerr := q.listMemoriesByAgentAndPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMemoriesByAgentAndPathStmt: %w", cerr)
		}
	}
	if q.listMemoriesByCategoryStmt != nil {
		if cerr := q.listMemoriesByCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMemoriesByCategoryStmt: %w", cerr)
		}
	}
	if q.listMemoriesByPathStmt != nil {
		if cerr := q.listMemoriesByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMemoriesByPathStmt: %w", cerr)
		}
	}
	if q.listMessagesBySessionStmt != nil {
		if cerr := q.listMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.listSessionsStmt != nil {
		if cerr := q.listSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsStmt: %w", cerr)
		}
	}
	if q.listSessionsByAgentStmt != nil {
		if cerr := q.listSessionsByAgentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsByAgentStmt: %w", cerr)
		}
	}
	if q.listSessionsBySourceStmt != nil {
		if cerr := q.listSessionsBySourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsBySourceStmt: %w", cerr)
		}
	}
	if q.pruneFlowRunsByAgeStmt != nil {
		if cerr := q.pruneFlowRunsByAgeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing pruneFlowRunsByAgeStmt: %w", cerr)
		}
	}
	if q.pruneFlowRunsByCountStmt != nil {
		if cerr := q.pruneFlowRunsByCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing pruneFlowRunsByCountStmt: %w", cerr)
		}
	}
	if q.searchSessionsByTitleStmt != nil {
		if cerr := q.searchSessionsByTitleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchSessionsByTitleStmt: %w", cerr)
		}
	}
	if q.supersedeMemoryStmt != nil {
		if cerr := q.supersedeMemoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing supersedeMemoryStmt: %w", cerr)
		}
	}
	if q.updateMemoryStmt != nil {
		if cerr := q.updateMemoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMemoryStmt: %w", cerr)
		}
	}
	if q.updateMemoryAccessStmt != nil {
		if cerr := q.updateMemoryAccessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMemoryAccessStmt: %w", cerr)
		}
	}
	if q.updateMessageStmt != nil {
		if cerr := q.updateMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMessageStmt: %w", cerr)
		}
	}
	if q.updateSessionStmt != nil {
		if cerr := q.updateSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionStmt: %w", cerr)
		}
	}
	if q.updateSessionTitleStmt != nil {
		if cerr := q.updateSessionTitleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionTitleStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                     DBTX
	tx                                     *sql.Tx
	clearAllMemoriesStmt                   *sql.Stmt
	clearMemoriesByAgentStmt               *sql.Stmt
	completeFlowRunStmt                    *sql.Stmt
	countFlowRunsStmt                      *sql.Stmt
	countFlowRunsByNameStmt                *sql.Stmt
	countFlowRunsByStatusStmt              *sql.Stmt
	countMemoriesStmt                      *sql.Stmt
	countMemoriesByAgentStmt               *sql.Stmt
	countMessagesBySessionStmt             *sql.Stmt
	countSessionsStmt                      *sql.Stmt
	countSessionsByAgentStmt               *sql.Stmt
	countSessionsBySourceStmt              *sql.Stmt
	createEdgeStmt                         *sql.Stmt
	createFlowRunStmt                      *sql.Stmt
	createMemoryStmt                       *sql.Stmt
	createMessageStmt                      *sql.Stmt
	createSessionStmt                      *sql.Stmt
	deleteEdgeStmt                         *sql.Stmt
	deleteEdgesBySessionStmt               *sql.Stmt
	deleteFlowRunStmt                      *sql.Stmt
	deleteMemoryStmt                       *sql.Stmt
	deleteMessageStmt                      *sql.Stmt
	deleteMessagesBySessionStmt            *sql.Stmt
	deleteSessionStmt                      *sql.Stmt
	forgetMemoryStmt                       *sql.Stmt
	getAllActiveMemoriesWithEmbeddingsStmt *sql.Stmt
	getChildEdgesStmt                      *sql.Stmt
	getFlowRunStmt                         *sql.Stmt
	getFlowRunByPrefixStmt                 *sql.Stmt
	getLastFlowRunStmt                     *sql.Stmt
	getMemoriesForSearchStmt               *sql.Stmt
	getMemoryStmt                          *sql.Stmt
	getMemoryHistoryStmt                   *sql.Stmt
	getMessageStmt                         *sql.Stmt
	getParentEdgesStmt                     *sql.Stmt
	getSessionStmt                         *sql.Stmt
	getSessionByPrefixStmt                 *sql.Stmt
	listFlowRunsStmt                       *sql.Stmt
	listFlowRunsByNameStmt                 *sql.Stmt
	listFlowRunsBySessionStmt              *sql.Stmt
	listFlowRunsByStatusStmt               *sql.Stmt
	listMemoriesStmt                       *sql.Stmt
	listMemoriesByAgentStmt                *sql.Stmt
	listMemoriesByAgentAndPathStmt         *sql.Stmt
	listMemoriesByCategoryStmt             *sql.Stmt
	listMemoriesByPathStmt                 *sql.Stmt
	listMessagesBySessionStmt              *sql.Stmt
	listSessionsStmt                       *sql.Stmt
	listSessionsByAgentStmt                *sql.Stmt
	listSessionsBySourceStmt               *sql.Stmt
	pruneFlowRunsByAgeStmt                 *sql.Stmt
	pruneFlowRunsByCountStmt               *sql.Stmt
	searchSessionsByTitleStmt              *sql.Stmt
	supersedeMemoryStmt                    *sql.Stmt
	updateMemoryStmt                       *sql.Stmt
	updateMemoryAccessStmt                 *sql.Stmt
	updateMessageStmt                      *sql.Stmt
	updateSessionStmt                      *sql.Stmt
	updateSessionTitleStmt                 *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                     tx,
		tx:                                     tx,
		clearAllMemoriesStmt:                   q.clearAllMemoriesStmt,
		clearMemoriesByAgentStmt:               q.clearMemoriesByAgentStmt,
		completeFlowRunStmt:                    q.completeFlowRunStmt,
		countFlowRunsStmt:                      q.countFlowRunsStmt,
		countFlowRunsByNameStmt:                q.countFlowRunsByNameStmt,
		countFlowRunsByStatusStmt:              q.countFlowRunsByStatusStmt,
		countMemoriesStmt:                      q.countMemoriesStmt,
		countMemoriesByAgentStmt:               q.countMemoriesByAgentStmt,
		countMessagesBySessionStmt:             q.countMessagesBySessionStmt,
		countSessionsStmt:                      q.countSessionsStmt,
		countSessionsByAgentStmt:               q.countSessionsByAgentStmt,
		countSessionsBySourceStmt:              q.countSessionsBySourceStmt,
		createEdgeStmt:                         q.createEdgeStmt,
		createFlowRunStmt:                      q.createFlowRunStmt,
		createMemoryStmt:                       q.createMemoryStmt,
		createMessageStmt:                      q.createMessageStmt,
		createSessionStmt:                      q.createSessionStmt,
		deleteEdgeStmt:                         q.deleteEdgeStmt,
		deleteEdgesBySessionStmt:               q.deleteEdgesBySessionStmt,
		deleteFlowRunStmt:                      q.deleteFlowRunStmt,
		deleteMemoryStmt:                       q.deleteMemoryStmt,
		deleteMessageStmt:                      q.deleteMessageStmt,
		deleteMessagesBySessionStmt:            q.deleteMessagesBySessionStmt,
		deleteSessionStmt:                      q.deleteSessionStmt,
		forgetMemoryStmt:                       q.forgetMemoryStmt,
		getAllActiveMemoriesWithEmbeddingsStmt: q.getAllActiveMemoriesWithEmbeddingsStmt,
		getChildEdgesStmt:                      q.getChildEdgesStmt,
		getFlowRunStmt:                         q.getFlowRunStmt,
		getFlowRunByPrefixStmt:                 q.getFlowRunByPrefixStmt,
		getLastFlowRunStmt:                     q.getLastFlowRunStmt,
		getMemoriesForSearchStmt:               q.getMemoriesForSearchStmt,
		getMemoryStmt:                          q.getMemoryStmt,
		getMemoryHistoryStmt:                   q.getMemoryHistoryStmt,
		getMessageStmt:                         q.getMessageStmt,
		getParentEdgesStmt:                     q.getParentEdgesStmt,
		getSessionStmt:                         q.getSessionStmt,
		getSessionByPrefixStmt:                 q.getSessionByPrefixStmt,
		listFlowRunsStmt:                       q.listFlowRunsStmt,
		listFlowRunsByNameStmt:                 q.listFlowRunsByNameStmt,
		listFlowRunsBySessionStmt:              q.listFlowRunsBySessionStmt,
		listFlowRunsByStatusStmt:               q.listFlowRunsByStatusStmt,
		listMemoriesStmt:                       q.listMemoriesStmt,
		listMemoriesByAgentStmt:                q.listMemoriesByAgentStmt,
		listMemoriesByAgentAndPathStmt:         q.listMemoriesByAgentAndPathStmt,
		listMemoriesByCategoryStmt:             q.listMemoriesByCategoryStmt,
		listMemoriesByPathStmt:                 q.listMemoriesByPathStmt,
		listMessagesBySessionStmt:              q.listMessagesBySessionStmt,
		listSessionsStmt:                       q.listSessionsStmt,
		listSessionsByAgentStmt:                q.listSessionsByAgentStmt,
		listSessionsBySourceStmt:               q.listSessionsBySourceStmt,
		pruneFlowRunsByAgeStmt:                 q.pruneFlowRunsByAgeStmt,
		pruneFlowRunsByCountStmt:               q.pruneFlowRunsByCountStmt,
		searchSessionsByTitleStmt:              q.searchSessionsByTitleStmt,
		supersedeMemoryStmt:                    q.supersedeMemoryStmt,
		updateMemoryStmt:                       q.updateMemoryStmt,
		updateMemoryAccessStmt:                 q.updateMemoryAccessStmt,
		updateMessageStmt:                      q.updateMessageStmt,
		updateSessionStmt:                      q.updateSessionStmt,
		updateSessionTitleStmt:                 q.updateSessionTitleStmt,
	}
}
