// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: edges.sql

package db

import (
	"context"
	"database/sql"
)

const createEdge = `-- name: CreateEdge :exec
INSERT INTO session_edges (
    parent_id,
    child_id,
    edge_type,
    trigger_message_id,
    created_at
) VALUES (
    ?1, ?2, ?3, ?4, strftime('%s', 'now')
)
`

type CreateEdgeParams struct {
	ParentID         string         `json:"parent_id"`
	ChildID          string         `json:"child_id"`
	EdgeType         string         `json:"edge_type"`
	TriggerMessageID sql.NullString `json:"trigger_message_id"`
}

func (q *Queries) CreateEdge(ctx context.Context, arg CreateEdgeParams) error {
	_, err := q.exec(ctx, q.createEdgeStmt, createEdge,
		arg.ParentID,
		arg.ChildID,
		arg.EdgeType,
		arg.TriggerMessageID,
	)
	return err
}

const deleteEdge = `-- name: DeleteEdge :exec
DELETE FROM session_edges WHERE parent_id = ?1 AND child_id = ?2
`

type DeleteEdgeParams struct {
	ParentID string `json:"parent_id"`
	ChildID  string `json:"child_id"`
}

func (q *Queries) DeleteEdge(ctx context.Context, arg DeleteEdgeParams) error {
	_, err := q.exec(ctx, q.deleteEdgeStmt, deleteEdge, arg.ParentID, arg.ChildID)
	return err
}

const deleteEdgesBySession = `-- name: DeleteEdgesBySession :exec
DELETE FROM session_edges WHERE parent_id = ?1 OR child_id = ?1
`

func (q *Queries) DeleteEdgesBySession(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteEdgesBySessionStmt, deleteEdgesBySession, sessionID)
	return err
}

const getChildEdges = `-- name: GetChildEdges :many
SELECT parent_id, child_id, edge_type, trigger_message_id, created_at FROM session_edges WHERE parent_id = ?1
`

func (q *Queries) GetChildEdges(ctx context.Context, parentID string) ([]SessionEdge, error) {
	rows, err := q.query(ctx, q.getChildEdgesStmt, getChildEdges, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionEdge{}
	for rows.Next() {
		var i SessionEdge
		if err := rows.Scan(
			&i.ParentID,
			&i.ChildID,
			&i.EdgeType,
			&i.TriggerMessageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParentEdges = `-- name: GetParentEdges :many
SELECT parent_id, child_id, edge_type, trigger_message_id, created_at FROM session_edges WHERE child_id = ?1
`

func (q *Queries) GetParentEdges(ctx context.Context, childID string) ([]SessionEdge, error) {
	rows, err := q.query(ctx, q.getParentEdgesStmt, getParentEdges, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionEdge{}
	for rows.Next() {
		var i SessionEdge
		if err := rows.Scan(
			&i.ParentID,
			&i.ChildID,
			&i.EdgeType,
			&i.TriggerMessageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
