// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: flow_runs.sql

package db

import (
	"context"
	"database/sql"
)

const completeFlowRun = `-- name: CompleteFlowRun :one
UPDATE flow_runs SET
    status = ?1,
    exit_code = ?2,
    error_message = ?3,
    output_json = ?4,
    stderr_log = ?5,
    output_validated = ?6,
    finished_at = ?7,
    duration_ms = ?8
WHERE id = ?9
RETURNING id, flow_name, flow_path, flow_source, status, exit_code, error_message, input_json, output_json, stderr_log, started_at, finished_at, duration_ms, parent_run_id, session_id, input_validated, output_validated
`

type CompleteFlowRunParams struct {
	Status          string         `json:"status"`
	ExitCode        sql.NullInt64  `json:"exit_code"`
	ErrorMessage    sql.NullString `json:"error_message"`
	OutputJson      sql.NullString `json:"output_json"`
	StderrLog       sql.NullString `json:"stderr_log"`
	OutputValidated int64          `json:"output_validated"`
	FinishedAt      sql.NullInt64  `json:"finished_at"`
	DurationMs      sql.NullInt64  `json:"duration_ms"`
	ID              string         `json:"id"`
}

func (q *Queries) CompleteFlowRun(ctx context.Context, arg CompleteFlowRunParams) (FlowRun, error) {
	row := q.queryRow(ctx, q.completeFlowRunStmt, completeFlowRun,
		arg.Status,
		arg.ExitCode,
		arg.ErrorMessage,
		arg.OutputJson,
		arg.StderrLog,
		arg.OutputValidated,
		arg.FinishedAt,
		arg.DurationMs,
		arg.ID,
	)
	var i FlowRun
	err := row.Scan(
		&i.ID,
		&i.FlowName,
		&i.FlowPath,
		&i.FlowSource,
		&i.Status,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.InputJson,
		&i.OutputJson,
		&i.StderrLog,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.ParentRunID,
		&i.SessionID,
		&i.InputValidated,
		&i.OutputValidated,
	)
	return i, err
}

const countFlowRuns = `-- name: CountFlowRuns :one
SELECT COUNT(*) FROM flow_runs
`

func (q *Queries) CountFlowRuns(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countFlowRunsStmt, countFlowRuns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFlowRunsByName = `-- name: CountFlowRunsByName :one
SELECT COUNT(*) FROM flow_runs WHERE flow_name = ?1
`

func (q *Queries) CountFlowRunsByName(ctx context.Context, flowName string) (int64, error) {
	row := q.queryRow(ctx, q.countFlowRunsByNameStmt, countFlowRunsByName, flowName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFlowRunsByStatus = `-- name: CountFlowRunsByStatus :one
SELECT COUNT(*) FROM flow_runs WHERE status = ?1
`

func (q *Queries) CountFlowRunsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.queryRow(ctx, q.countFlowRunsByStatusStmt, countFlowRunsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFlowRun = `-- name: CreateFlowRun :one
INSERT INTO flow_runs (
    id,
    flow_name,
    flow_path,
    flow_source,
    status,
    input_json,
    input_validated,
    started_at,
    parent_run_id,
    session_id
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    'running',
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
) RETURNING id, flow_name, flow_path, flow_source, status, exit_code, error_message, input_json, output_json, stderr_log, started_at, finished_at, duration_ms, parent_run_id, session_id, input_validated, output_validated
`

type CreateFlowRunParams struct {
	ID             string         `json:"id"`
	FlowName       string         `json:"flow_name"`
	FlowPath       string         `json:"flow_path"`
	FlowSource     string         `json:"flow_source"`
	InputJson      sql.NullString `json:"input_json"`
	InputValidated int64          `json:"input_validated"`
	StartedAt      int64          `json:"started_at"`
	ParentRunID    sql.NullString `json:"parent_run_id"`
	SessionID      sql.NullString `json:"session_id"`
}

func (q *Queries) CreateFlowRun(ctx context.Context, arg CreateFlowRunParams) (FlowRun, error) {
	row := q.queryRow(ctx, q.createFlowRunStmt, createFlowRun,
		arg.ID,
		arg.FlowName,
		arg.FlowPath,
		arg.FlowSource,
		arg.InputJson,
		arg.InputValidated,
		arg.StartedAt,
		arg.ParentRunID,
		arg.SessionID,
	)
	var i FlowRun
	err := row.Scan(
		&i.ID,
		&i.FlowName,
		&i.FlowPath,
		&i.FlowSource,
		&i.Status,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.InputJson,
		&i.OutputJson,
		&i.StderrLog,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.ParentRunID,
		&i.SessionID,
		&i.InputValidated,
		&i.OutputValidated,
	)
	return i, err
}

const deleteFlowRun = `-- name: DeleteFlowRun :exec
DELETE FROM flow_runs WHERE id = ?1
`

func (q *Queries) DeleteFlowRun(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteFlowRunStmt, deleteFlowRun, id)
	return err
}

const getFlowRun = `-- name: GetFlowRun :one
SELECT id, flow_name, flow_path, flow_source, status, exit_code, error_message, input_json, output_json, stderr_log, started_at, finished_at, duration_ms, parent_run_id, session_id, input_validated, output_validated FROM flow_runs WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetFlowRun(ctx context.Context, id string) (FlowRun, error) {
	row := q.queryRow(ctx, q.getFlowRunStmt, getFlowRun, id)
	var i FlowRun
	err := row.Scan(
		&i.ID,
		&i.FlowName,
		&i.FlowPath,
		&i.FlowSource,
		&i.Status,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.InputJson,
		&i.OutputJson,
		&i.StderrLog,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.ParentRunID,
		&i.SessionID,
		&i.InputValidated,
		&i.OutputValidated,
	)
	return i, err
}

const getFlowRunByPrefix = `-- name: GetFlowRunByPrefix :many
SELECT id, flow_name, flow_path, flow_source, status, exit_code, error_message, input_json, output_json, stderr_log, started_at, finished_at, duration_ms, parent_run_id, session_id, input_validated, output_validated FROM flow_runs WHERE id LIKE ?1 || '%' ORDER BY started_at DESC LIMIT 10
`

func (q *Queries) GetFlowRunByPrefix(ctx context.Context, prefix sql.NullString) ([]FlowRun, error) {
	rows, err := q.query(ctx, q.getFlowRunByPrefixStmt, getFlowRunByPrefix, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlowRun{}
	for rows.Next() {
		var i FlowRun
		if err := rows.Scan(
			&i.ID,
			&i.FlowName,
			&i.FlowPath,
			&i.FlowSource,
			&i.Status,
			&i.ExitCode,
			&i.ErrorMessage,
			&i.InputJson,
			&i.OutputJson,
			&i.StderrLog,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ParentRunID,
			&i.SessionID,
			&i.InputValidated,
			&i.OutputValidated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastFlowRun = `-- name: GetLastFlowRun :one
SELECT id, flow_name, flow_path, flow_source, status, exit_code, error_message, input_json, output_json, stderr_log, started_at, finished_at, duration_ms, parent_run_id, session_id, input_validated, output_validated FROM flow_runs WHERE flow_name = ?1 ORDER BY started_at DESC LIMIT 1
`

func (q *Queries) GetLastFlowRun(ctx context.Context, flowName string) (FlowRun, error) {
	row := q.queryRow(ctx, q.getLastFlowRunStmt, getLastFlowRun, flowName)
	var i FlowRun
	err := row.Scan(
		&i.ID,
		&i.FlowName,
		&i.FlowPath,
		&i.FlowSource,
		&i.Status,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.InputJson,
		&i.OutputJson,
		&i.StderrLog,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.ParentRunID,
		&i.SessionID,
		&i.InputValidated,
		&i.OutputValidated,
	)
	return i, err
}

const listFlowRuns = `-- name: ListFlowRuns :many
SELECT id, flow_name, flow_path, flow_source, status, exit_code, error_message, input_json, output_json, stderr_log, started_at, finished_at, duration_ms, parent_run_id, session_id, input_validated, output_validated FROM flow_runs ORDER BY started_at DESC LIMIT ?1
`

func (q *Queries) ListFlowRuns(ctx context.Context, limit int64) ([]FlowRun, error) {
	rows, err := q.query(ctx, q.listFlowRunsStmt, listFlowRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlowRun{}
	for rows.Next() {
		var i FlowRun
		if err := rows.Scan(
			&i.ID,
			&i.FlowName,
			&i.FlowPath,
			&i.FlowSource,
			&i.Status,
			&i.ExitCode,
			&i.ErrorMessage,
			&i.InputJson,
			&i.OutputJson,
			&i.StderrLog,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ParentRunID,
			&i.SessionID,
			&i.InputValidated,
			&i.OutputValidated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlowRunsByName = `-- name: ListFlowRunsByName :many
SELECT id, flow_name, flow_path, flow_source, status, exit_code, error_message, input_json, output_json, stderr_log, started_at, finished_at, duration_ms, parent_run_id, session_id, input_validated, output_validated FROM flow_runs WHERE flow_name = ?1 ORDER BY started_at DESC LIMIT ?2
`

type ListFlowRunsByNameParams struct {
	FlowName string `json:"flow_name"`
	Limit    int64  `json:"limit"`
}

func (q *Queries) ListFlowRunsByName(ctx context.Context, arg ListFlowRunsByNameParams) ([]FlowRun, error) {
	rows, err := q.query(ctx, q.listFlowRunsByNameStmt, listFlowRunsByName, arg.FlowName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlowRun{}
	for rows.Next() {
		var i FlowRun
		if err := rows.Scan(
			&i.ID,
			&i.FlowName,
			&i.FlowPath,
			&i.FlowSource,
			&i.Status,
			&i.ExitCode,
			&i.ErrorMessage,
			&i.InputJson,
			&i.OutputJson,
			&i.StderrLog,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ParentRunID,
			&i.SessionID,
			&i.InputValidated,
			&i.OutputValidated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlowRunsBySession = `-- name: ListFlowRunsBySession :many
SELECT id, flow_name, flow_path, flow_source, status, exit_code, error_message, input_json, output_json, stderr_log, started_at, finished_at, duration_ms, parent_run_id, session_id, input_validated, output_validated FROM flow_runs WHERE session_id = ?1 ORDER BY started_at DESC
`

func (q *Queries) ListFlowRunsBySession(ctx context.Context, sessionID sql.NullString) ([]FlowRun, error) {
	rows, err := q.query(ctx, q.listFlowRunsBySessionStmt, listFlowRunsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlowRun{}
	for rows.Next() {
		var i FlowRun
		if err := rows.Scan(
			&i.ID,
			&i.FlowName,
			&i.FlowPath,
			&i.FlowSource,
			&i.Status,
			&i.ExitCode,
			&i.ErrorMessage,
			&i.InputJson,
			&i.OutputJson,
			&i.StderrLog,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ParentRunID,
			&i.SessionID,
			&i.InputValidated,
			&i.OutputValidated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlowRunsByStatus = `-- name: ListFlowRunsByStatus :many
SELECT id, flow_name, flow_path, flow_source, status, exit_code, error_message, input_json, output_json, stderr_log, started_at, finished_at, duration_ms, parent_run_id, session_id, input_validated, output_validated FROM flow_runs WHERE status = ?1 ORDER BY started_at DESC LIMIT ?2
`

type ListFlowRunsByStatusParams struct {
	Status string `json:"status"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListFlowRunsByStatus(ctx context.Context, arg ListFlowRunsByStatusParams) ([]FlowRun, error) {
	rows, err := q.query(ctx, q.listFlowRunsByStatusStmt, listFlowRunsByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlowRun{}
	for rows.Next() {
		var i FlowRun
		if err := rows.Scan(
			&i.ID,
			&i.FlowName,
			&i.FlowPath,
			&i.FlowSource,
			&i.Status,
			&i.ExitCode,
			&i.ErrorMessage,
			&i.InputJson,
			&i.OutputJson,
			&i.StderrLog,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ParentRunID,
			&i.SessionID,
			&i.InputValidated,
			&i.OutputValidated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneFlowRunsByAge = `-- name: PruneFlowRunsByAge :exec
DELETE FROM flow_runs WHERE started_at < ?1
`

func (q *Queries) PruneFlowRunsByAge(ctx context.Context, cutoffTimestamp int64) error {
	_, err := q.exec(ctx, q.pruneFlowRunsByAgeStmt, pruneFlowRunsByAge, cutoffTimestamp)
	return err
}

const pruneFlowRunsByCount = `-- name: PruneFlowRunsByCount :exec
DELETE FROM flow_runs WHERE id NOT IN (
    SELECT id FROM flow_runs ORDER BY started_at DESC LIMIT ?1
)
`

func (q *Queries) PruneFlowRunsByCount(ctx context.Context, keepCount int64) error {
	_, err := q.exec(ctx, q.pruneFlowRunsByCountStmt, pruneFlowRunsByCount, keepCount)
	return err
}
