// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Message struct {
	ID         string         `json:"id"`
	SessionID  string         `json:"session_id"`
	Role       string         `json:"role"`
	Parts      string         `json:"parts"`
	Model      sql.NullString `json:"model"`
	Provider   sql.NullString `json:"provider"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
}

type Session struct {
	ID               string         `json:"id"`
	AgentHandle      string         `json:"agent_handle"`
	Title            string         `json:"title"`
	InputSchema      sql.NullString `json:"input_schema"`
	OutputSchema     sql.NullString `json:"output_schema"`
	StructuredInput  sql.NullString `json:"structured_input"`
	StructuredOutput sql.NullString `json:"structured_output"`
	ChainDepth       int64          `json:"chain_depth"`
	ChainSource      sql.NullString `json:"chain_source"`
	MessageCount     int64          `json:"message_count"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	FinishedAt       sql.NullInt64  `json:"finished_at"`
	Plan             sql.NullString `json:"plan"`
	Source           string         `json:"source"`
}

type SessionEdge struct {
	ParentID         string         `json:"parent_id"`
	ChildID          string         `json:"child_id"`
	EdgeType         string         `json:"edge_type"`
	TriggerMessageID sql.NullString `json:"trigger_message_id"`
	CreatedAt        int64          `json:"created_at"`
}
