// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AgentCapability struct {
	ID          string  `json:"id"`
	AgentID     string  `json:"agent_id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Confidence  float64 `json:"confidence"`
	Source      string  `json:"source"`
	Embedding   []byte  `json:"embedding"`
	InputHash   string  `json:"input_hash"`
	CreatedAt   int64   `json:"created_at"`
	UpdatedAt   int64   `json:"updated_at"`
}

type AgentRefinement struct {
	ID             string `json:"id"`
	AgentID        string `json:"agent_id"`
	PreviousPrompt string `json:"previous_prompt"`
	NewPrompt      string `json:"new_prompt"`
	Reason         string `json:"reason"`
	CreatedAt      int64  `json:"created_at"`
}

type AyoCreatedAgent struct {
	AgentID           string         `json:"agent_id"`
	AgentHandle       string         `json:"agent_handle"`
	CreatedBy         string         `json:"created_by"`
	CreationReason    sql.NullString `json:"creation_reason"`
	OriginalPrompt    string         `json:"original_prompt"`
	InvocationCount   int64          `json:"invocation_count"`
	SuccessCount      int64          `json:"success_count"`
	FailureCount      int64          `json:"failure_count"`
	LastUsedAt        sql.NullInt64  `json:"last_used_at"`
	RefinementCount   int64          `json:"refinement_count"`
	CurrentPromptHash sql.NullString `json:"current_prompt_hash"`
	Confidence        float64        `json:"confidence"`
	IsArchived        int64          `json:"is_archived"`
	PromotedTo        sql.NullString `json:"promoted_to"`
	CreatedAt         int64          `json:"created_at"`
	UpdatedAt         int64          `json:"updated_at"`
}

type FlowRun struct {
	ID              string         `json:"id"`
	FlowName        string         `json:"flow_name"`
	FlowPath        string         `json:"flow_path"`
	FlowSource      string         `json:"flow_source"`
	Status          string         `json:"status"`
	ExitCode        sql.NullInt64  `json:"exit_code"`
	ErrorMessage    sql.NullString `json:"error_message"`
	InputJson       sql.NullString `json:"input_json"`
	OutputJson      sql.NullString `json:"output_json"`
	StderrLog       sql.NullString `json:"stderr_log"`
	StartedAt       int64          `json:"started_at"`
	FinishedAt      sql.NullInt64  `json:"finished_at"`
	DurationMs      sql.NullInt64  `json:"duration_ms"`
	ParentRunID     sql.NullString `json:"parent_run_id"`
	SessionID       sql.NullString `json:"session_id"`
	InputValidated  int64          `json:"input_validated"`
	OutputValidated int64          `json:"output_validated"`
}

type Memory struct {
	ID                 string          `json:"id"`
	AgentHandle        sql.NullString  `json:"agent_handle"`
	PathScope          sql.NullString  `json:"path_scope"`
	Content            string          `json:"content"`
	Category           string          `json:"category"`
	Embedding          []byte          `json:"embedding"`
	SourceSessionID    sql.NullString  `json:"source_session_id"`
	SourceMessageID    sql.NullString  `json:"source_message_id"`
	CreatedAt          int64           `json:"created_at"`
	UpdatedAt          int64           `json:"updated_at"`
	Confidence         sql.NullFloat64 `json:"confidence"`
	LastAccessedAt     sql.NullInt64   `json:"last_accessed_at"`
	AccessCount        sql.NullInt64   `json:"access_count"`
	SupersedesID       sql.NullString  `json:"supersedes_id"`
	SupersededByID     sql.NullString  `json:"superseded_by_id"`
	SupersessionReason sql.NullString  `json:"supersession_reason"`
	Status             sql.NullString  `json:"status"`
	SquadName          sql.NullString  `json:"squad_name"`
}

type Message struct {
	ID         string         `json:"id"`
	SessionID  string         `json:"session_id"`
	Role       string         `json:"role"`
	Parts      string         `json:"parts"`
	Model      sql.NullString `json:"model"`
	Provider   sql.NullString `json:"provider"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
}

type Session struct {
	ID               string         `json:"id"`
	AgentHandle      string         `json:"agent_handle"`
	Title            string         `json:"title"`
	Source           string         `json:"source"`
	InputSchema      sql.NullString `json:"input_schema"`
	OutputSchema     sql.NullString `json:"output_schema"`
	StructuredInput  sql.NullString `json:"structured_input"`
	StructuredOutput sql.NullString `json:"structured_output"`
	ChainDepth       int64          `json:"chain_depth"`
	ChainSource      sql.NullString `json:"chain_source"`
	MessageCount     int64          `json:"message_count"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	FinishedAt       sql.NullInt64  `json:"finished_at"`
}

type SessionEdge struct {
	ParentID         string         `json:"parent_id"`
	ChildID          string         `json:"child_id"`
	EdgeType         string         `json:"edge_type"`
	TriggerMessageID sql.NullString `json:"trigger_message_id"`
	CreatedAt        int64          `json:"created_at"`
}

type TriggerStat struct {
	TriggerID           string        `json:"trigger_id"`
	FlowName            string        `json:"flow_name"`
	TriggerType         string        `json:"trigger_type"`
	RunCount            int64         `json:"run_count"`
	SuccessCount        int64         `json:"success_count"`
	FailureCount        int64         `json:"failure_count"`
	RunsBeforePermanent sql.NullInt64 `json:"runs_before_permanent"`
	IsPermanent         int64         `json:"is_permanent"`
	LastRunAt           sql.NullInt64 `json:"last_run_at"`
	LastSuccessAt       sql.NullInt64 `json:"last_success_at"`
	LastFailureAt       sql.NullInt64 `json:"last_failure_at"`
	AvgDurationMs       sql.NullInt64 `json:"avg_duration_ms"`
	CreatedAt           int64         `json:"created_at"`
	UpdatedAt           int64         `json:"updated_at"`
}
