// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountMessagesBySession(ctx context.Context, sessionID string) (int64, error)
	CountSessions(ctx context.Context) (int64, error)
	CountSessionsByAgent(ctx context.Context, agentHandle string) (int64, error)
	CreateEdge(ctx context.Context, arg CreateEdgeParams) error
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteEdge(ctx context.Context, arg DeleteEdgeParams) error
	DeleteEdgesBySession(ctx context.Context, sessionID string) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteMessagesBySession(ctx context.Context, sessionID string) error
	DeleteSession(ctx context.Context, id string) error
	GetChildEdges(ctx context.Context, parentID string) ([]SessionEdge, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetParentEdges(ctx context.Context, childID string) ([]SessionEdge, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetSessionByPrefix(ctx context.Context, prefix sql.NullString) ([]Session, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListSessions(ctx context.Context, limit int64) ([]Session, error)
	ListSessionsByAgent(ctx context.Context, arg ListSessionsByAgentParams) ([]Session, error)
	SearchSessionsByTitle(ctx context.Context, arg SearchSessionsByTitleParams) ([]Session, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateSessionTitle(ctx context.Context, arg UpdateSessionTitleParams) error
}

var _ Querier = (*Queries)(nil)
